### ISSUE TITLE
Impossible to deploy vm on exisitng (remote) nixos

### ISSUE THREAD

**Issue by adfaure** [NixOS/nixops#1026]
Hi,

this is my nix file:
```nix
{
  network.description = "Web server";

  webserver =
    { config, pkgs, ... }:
    {
      services.httpd.enable = true;
      imports = [
        ./configuration-vultr.nix
      ];
      deployment.targetHost = "xx.xx.xx.xx";
      services.httpd.adminAddr = "alice@example.org";
      services.httpd.documentRoot = "${pkgs.valgrind.doc}/share/doc/valgrind/html";
      networking.firewall.allowedTCPPorts = [ 80 ];
    };
}
```

Hi created the host with: `nixops create configuration.nix -d v`
and when I want to deploy I have the following log:

```
adfaure@adchire> nixops deploy -d v
webserver> generating new SSH keypair... done
webserver> setting state version to 18.03
webserver> waiting for SSH...
building all machine configurations...
error: The option `network' defined in `/home/adfaure/nix_configuration/deployments/configuration-vultr.nix' does not exist.
(use '--show-trace' to show detailed location information)
error: unable to build all machine configurations
```

and the full trace 
```
[1] adfaure@adchire> nixops deploy -d v --show-trace
building all machine configurations...
error: while evaluating the attribute 'buildCommand' of the derivation 'nixops-machines' at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating anonymous function at /nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/share/nix/nixops/eval-machine-info.nix:368:46, called from undefined position:
while evaluating the attribute 'config.system.build.toplevel' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix:57:5:
while evaluating the attribute 'config' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:87:25:
while evaluating 'yieldConfig' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:74:29, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:73:16:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:80:24, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:80:11:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:81:26, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:81:13:
The option `network' defined in `/home/adfaure/nix_configuration/deployments/configuration-vultr.nix' does not exist.
Traceback (most recent call last):
  File "/nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/bin/..nixops-wrapped-wrapped", line 985, in <module>
    args.op()
  File "/nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/bin/..nixops-wrapped-wrapped", line 407, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/lib/python2.7/site-packages/nixops/deployment.py", line 1051, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/lib/python2.7/site-packages/nixops/deployment.py", line 1040, in run_with_notify
    f()
  File "/nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/lib/python2.7/site-packages/nixops/deployment.py", line 1051, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/lib/python2.7/site-packages/nixops/deployment.py", line 991, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/0pd48alphnpv3fmdbczv61s78z4ld3hx-nixops-1.6/lib/python2.7/site-packages/nixops/deployment.py", line 659, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
[1] adfaure@adchire>    
```

Is it a bug ? Or maybe I am missing something. 
Thank you very much :)

details:
```
[130] adfaure@adchire> nixops --version
NixOps 1.6
```

**Comment by adfaure** [comment]
I found the issue... I miss spelled the path of the imported file.
Sorry for tho noise, I am closing the issue.
