### ISSUE TITLE
Exception: unable to get info on VirtualBox VM ‘backend2’

### ISSUE THREAD

**Issue by davidak** [NixOS/nixops#1097]
>The command nixops check checks the status of each machine in a deployment. It verifies that the machine still exists (i.e. hasn’t been destroyed outside of NixOps)

instead it crashes when i have deleted the machine in virtualbox!

```
[davidak@ethmoid:~/code/nixops]$ nixops check -d load-balancer
backend2> VBoxManage: error: Could not find a registered machine named 'nixops-1d068130-3522-11e9-89f9-024246453e35-backend2'
backend2> VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
backend2> VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2834 of file VBoxManageInfo.cpp
ssh: connect to host 192.168.56.108 port 22: Connection refused
Traceback (most recent call last):
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/bin/..nixops-wrapped-wrapped", line 990, in <module>
    args.op()
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/bin/..nixops-wrapped-wrapped", line 297, in op_check
    results = run_tasks(nr_workers=len(machines), tasks=machines, worker_fun=worker)
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/bin/..nixops-wrapped-wrapped", line 259, in worker
    res = m.check()
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/lib/python2.7/site-packages/nixops/backends/__init__.py", line 117, in check
    self._check(res)
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 449, in _check
    state = self._get_vm_state()
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 117, in _get_vm_state
    vminfo = self._get_vm_info(can_fail)
  File "/nix/store/ny77qvx9by0fh2fmm1lyayaki0fymsbr-nixops-1.6.1/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 107, in _get_vm_info
    raise Exception("unable to get info on VirtualBox VM ‘{0}’".format(self.name))
Exception: unable to get info on VirtualBox VM ‘backend2’
```
---
nix (Nix) 2.1.3
NixOS 18.09.2203.9bd45dddf81 (Jellyfish)
NixOps 1.6.1

**Comment by AmineChikhaoui** [comment]
should be fixed in e55aa716c6c890311f997b211cdab20445815f28
