### ISSUE TITLE
nixops virtualbox example fails with error mkOption called with unexpected arguments.

### ISSUE THREAD

**Issue by locallycompact** [NixOS/nixops#1107]
Hi, I'm using the standard VirtualBox example in the nixops manual and running into this.

```
lc@sunwell ~/gl> nixops deploy -d trivial --show-trace
building all machine configurations...
error: while evaluating the attribute 'buildCommand' of the derivation 'nixops-machines' at /nix/store/lbcw5zgr0sxp4zi18p5bzqydywq3sc5c-nixos-19.09pre170705.1233c8d9e9b/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating anonymous function at /nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/share/nix/nixops/eval-machine-info.nix:369:46, called from undefined position:
while evaluating the attribute 'config.system.build.toplevel' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:276:5:
while evaluating 'foldr' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:39:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:140:12:
while evaluating 'fold'' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:42:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:46:8:
while evaluating the attribute 'assertions' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:338:9:
while evaluating the option `assertions':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:375:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:364:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:350:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:350:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:417:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:351:62:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:488:14:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:488:14:
while evaluating the attribute 'boot.initrd.supportedFilesystems' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:338:9:
while evaluating the option `boot.initrd.supportedFilesystems':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:375:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:364:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:350:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:350:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:417:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:351:62:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:417:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:423:11:
while evaluating the attribute 'content' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:488:14:
while evaluating the attribute 'system.build.fileSystems' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/tasks/filesystems.nix:219:5:
while evaluating 'toposort' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:441:22, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/tasks/filesystems.nix:13:18:
while evaluating the attribute 'fileSystems' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating 'isType' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:14:18, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:76:14:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:237:39, called from undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:227:22, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:243:23:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:243:30, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:227:28:
while evaluating 'isType' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:14:18, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:243:33:
while evaluating the attribute 'options' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:226:37:
'mkOption' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/options.nix:30:5 called with unexpected argument 'options', at /nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/share/nix/nixops/gce.nix:382:19
Traceback (most recent call last):
  File "/nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/bin/..nixops-wrapped-wrapped", line 990, in <module>
    args.op()
  File "/nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/bin/..nixops-wrapped-wrapped", line 411, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 1056, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 1045, in run_with_notify
    f()
  File "/nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 1056, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 996, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/bsdxj77fn2ipwp65hz07h5bdr8gmbv7n-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 664, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
```

**Comment by gchinis** [comment]
I also experience this problem. Is it maybe related to #1086?

**Comment by delroth** [comment]
If you're using nixpkgs more recent than 18.09 you currently have to use nixopsUnstable. The latest stable release of nixops does not work with 19.03 or master.

**Comment by locallycompact** [comment]
Currently unable to install nixopsUnstable due to this error

```
sed: can't read azure/mgmt/compute/computemanagement.py: No such file or directory
setting SOURCE_DATE_EPOCH to timestamp 1546458756 of file azure-mgmt-resource-2.1.0/setup.cfg
patching sources
builder for '/nix/store/wbvwarpgp5wjfcl4jrfbabc3jc7r7xa7-python2.7-azure-mgmt-compute-4.4.0.drv' failed with exit code 2
cannot build derivation '/nix/store/nyf59z0r8f6751d9xk7z6663rpw7v1wx-nixops-1.6.1pre2728_8ed39f9.drv': 1 dependencies couldn't be built
```

**Comment by delroth** [comment]
That's unrelated to Nixops though, one of its dependencies is broken in Nixpkgs right now.

**Comment by charukiewicz** [comment]
For time time being, you can build the `nixopsUnstable` version of by switching to an older `nixpkgs` channel:

```
nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs
nix-channel --update nixpkgs
nix-env -iA nixpkgs.nixopsUnstable
```

This should install `nixops-1.6.1pre2706_d5ad09c`, as opposed to `nixops-1.6.1pre2728_8ed39f9`, which currently has a broken dependency.

**Comment by AmineChikhaoui** [comment]
This should be fixed in the latest release
