### ISSUE TITLE
VBoxManage: error: Resize medium operation for this format is not implemented yet!

### ISSUE THREAD

**Issue by davidak** [NixOS/nixops#1143]
I want to create a VM with 4 GB disk.

```
{
  target =
    { config, pkgs, ... }:
    { deployment.targetEnv = "virtualbox";
      deployment.virtualbox.disks.disk1.size = 4096;
    };
}
```

But it fails:

```
[davidak@ethmoid:~/code/nixops]$ nixops deploy -d targets
target> creating VirtualBox VM...
target> Virtual machine 'nixops-f69eceee-7251-11e9-ae57-02423d929eab-target' is created and registered.
target> UUID: c3d4b3ab-ab2a-4d81-b7a4-0af85eea9e20
target> Settings file: '/home/davidak/VirtualBox VMs/nixops-f69eceee-7251-11e9-ae57-02423d929eab-target/nixops-f69eceee-7251-11e9-ae57-02423d929eab-target.vbox'
target> creating disk ‘disk1’...
target> 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
target> Clone medium created in format 'VDI'. UUID: a1fbaa38-5642-410d-9b1a-2ddc1ffced5c
target> 0%...
target> Progress state: VBOX_E_NOT_SUPPORTED
target> VBoxManage: error: Resize medium operation for this format is not implemented yet!
Traceback (most recent call last):
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 996, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 969, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 288, in create
    self._logged_exec(["VBoxManage", "modifyhd", disk_path, "--resize", str(disk_def['size'])])
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 324, in _logged_exec
    return nixops.util.logged_exec(command, self.logger, **kwargs)
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/util.py", line 152, in logged_exec
    raise CommandFailed(err, res)
nixops.util.CommandFailed: command ‘['VBoxManage', 'modifyhd', '/home/davidak/VirtualBox VMs/nixops-f69eceee-7251-11e9-ae57-02423d929eab-target/disk1.vdi', '--resize', '4096']’ failed on machine ‘target’ (exit code 1)

```

**Comment by AmineChikhaoui** [comment]
The base image is currently 50Gb (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/virtualbox-image.nix#L15).
VirtualBox doesn't support shrinking the disk (see https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvdi), so you can only expand the disk:
>This option currently works only for VDI and VHD formats, and only for the dynamically allocated variants. It can only be used to expand, but not shrink, the capacity. For example, if you originally created a 10 GB disk which is now full, you can use the --resize 15360 command to change the capacity to 15 GB (15,360 MB) without having to create a new image and copy all data from within a virtual machine. Note however that this only changes the drive capacity. You will typically next need to use a partition management tool inside the guest to adjust the main partition to fill the drive.

So I think this is an expected behavior, to reduce the size you can likely create a different base image and modify the disk size there.
