### ISSUE TITLE
Could not resolve hostname services when using systemCronJobs

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixops#1176]
Deployment to virtual box stopped working for me. This includes both old and newly created machines. I haven't tried to deploy to anything else as I'm a bit afraid of what might happen.

The actual error is:

```
waiting for IP address...ssh: Could not resolve hostname services: Name or service not known
could not connect to ‘root@services’, retrying in 8 seconds...
```
Ending with python exception:

```
Traceback (most recent call last):
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 996, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 979, in worker
    os_release = r.run_command("cat /etc/os-release", capture_stdout=True)
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 337, in run_command
    return self.ssh.run_command(command, self.get_ssh_flags(), **kwargs)
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/ssh_util.py", line 280, in run_command
    master = self.get_master(flags, timeout, user)
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/ssh_util.py", line 200, in get_master
    compress=self._compress)
  File "/nix/store/mzhk7my6sxv6zidhkivhkw0wqn7rkc5j-nixops-1.7/lib/python2.7/site-packages/nixops/ssh_util.py", line 57, in __init__
    "‘{0}’".format(target)
nixops.ssh_util.SSHConnectionFailed: unable to start SSH master connection to ‘root@services’
````

vboxnet0.service service is running on the system.

## Update

After some debugging, I can confirm this is related to `services.cron.systemCronJobs` setting in deployment expression.

**Comment by turboMaCk** [comment]
works for me now, not sure what fixed it but closing.

**Comment by lontivero** [comment]
I am facing the exact same problem.
