### ISSUE TITLE
[Hetzner] Deployment fails complaning about GLIBC

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixops#1213]
Creating a deployment with the following config fails

```nix
{
    deployment.targetEnv = "hetzner";
    deployment.hetzner.mainIPv4 = "...";
    deployment.hetzner.partitions = ''
      clearpart --all --initlabel --drives=sda,sdb

      part swap1 --recommended --label=swap1 --fstype=swap --ondisk=sda
      part swap2 --recommended --label=swap2 --fstype=swap --ondisk=sdb

      part btrfs.1 --grow --ondisk=sda
      part btrfs.2 --grow --ondisk=sdb

      btrfs / --data=1 --metadata=1 --label=root btrfs.1 btrfs.2
    '';
    deployment.hetzner.createSubAccount = false;
}
```
Although I'm really not sure if the GLIBC error is from my machine or the server. But I've already launched it from nix-shell

```
neon> waiting for rescue system....[down]..................................................[up]
neon> building Nix bootstrap installer... done. (/nix/store/d5y1pxcbfyyzx7wci08bddiil80js3vp-hetzner-nixops-installer/bin/hetzner-bootstrap)
neon> creating nixbld group in rescue system... done.
neon> checking if tmpfs in rescue system is large enough... yes: 32188 MB
neon> copying bootstrap files to rescue system... done.
neon> partitioning disks... 
neon> Traceback (most recent call last):
neon>   File "/nix/store/2wdqimvfaz6axd16l0jbvng1fc5glhi0-nixpart-0.4.1/bin/.nixpart-wrapped", line 10, in <module>
neon>     from nixkickstart import NixKickstart
neon>   File "/nix/store/2wdqimvfaz6axd16l0jbvng1fc5glhi0-nixpart-0.4.1/lib/python2.7/site-packages/nixkickstart.py", line 24, in <module>
neon>     from blivet.deviceaction import *
neon>   File "/nix/store/agj5j1s7jmm84y0hbj6ily63bby4kl4g-blivet-0.17-1/lib/python2.7/site-packages/blivet/__init__.py", line 68, in <module>
neon>     from devices import *
neon>   File "/nix/store/agj5j1s7jmm84y0hbj6ily63bby4kl4g-blivet-0.17-1/lib/python2.7/site-packages/blivet/devices.py", line 103, in <module>
neon>     from devicelibs import mdraid
neon>   File "/nix/store/agj5j1s7jmm84y0hbj6ily63bby4kl4g-blivet-0.17-1/lib/python2.7/site-packages/blivet/devicelibs/mdraid.py", line 25, in <module>
neon>     from .. import util
neon>   File "/nix/store/agj5j1s7jmm84y0hbj6ily63bby4kl4g-blivet-0.17-1/lib/python2.7/site-packages/blivet/util.py", line 7, in <module>
neon>     from udev import udev_settle
neon>   File "/nix/store/agj5j1s7jmm84y0hbj6ily63bby4kl4g-blivet-0.17-1/lib/python2.7/site-packages/blivet/udev.py", line 30, in <module>
neon>     import pyudev
neon>   File "/nix/store/agj5j1s7jmm84y0hbj6ily63bby4kl4g-blivet-0.17-1/lib/python2.7/site-packages/blivet/pyudev.py", line 41, in <module>
neon>     libudev = CDLL(libudev)
neon>   File "/nix/store/496hlkwcniy4yi3nix0cps43a3ll2c11-python-2.7.17/lib/python2.7/ctypes/__init__.py", line 366, in __init__
neon>     self._handle = _dlopen(self._name, mode)
neon> OSError: /nix/store/xlxiw4rnxx2dksa91fizjzf7jb5nqghc-glibc-2.27/lib/libc.so.6: version `GLIBC_2.28' not found (required by /lib/x86_64-linux-gnu/libudev.so.1)
Traceback (most recent call last):
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 996, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 969, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/backends/hetzner.py", line 633, in create
    self.reboot_rescue(install=True, partitions=defn.partitions)
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/backends/hetzner.py", line 366, in reboot_rescue
    self._bootstrap_rescue(install, partitions)
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/backends/hetzner.py", line 287, in _bootstrap_rescue
    stdin_string=partitions)
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 337, in run_command
    return self.ssh.run_command(command, self.get_ssh_flags(), **kwargs)
  File "/nix/store/2m5y1bz8fdb3l2b72lgyg5wgp83v466k-nixops-1.7/lib/python2.7/site-packages/nixops/ssh_util.py", line 291, in run_command
    raise SSHCommandFailed(exc.message, exc.exitcode)
nixops.ssh_util.SSHCommandFailed: command ‘['ssh', '-oControlPath=/run/user/1000/nixops-ssh-tmpgDPLe0/master-socket', '-p', '22', '-o', 'LogLevel=quiet', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'GlobalKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=accept-new', '-p', '22', '-o', 'LogLevel=quiet', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'GlobalKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=accept-new', '-x', 'root@46.4.97.236', '--', 'export LANG= LC_ALL= LC_TIME=; nixpart -p -']’ failed on machine ‘neon’ (exit code 1)
```

**Comment by mkg20001** [comment]
After some digging I found that strangely it accesses the system libraries

```
root@rescue /nix # strace nixpart 2>&1 | grep /lib | grep -v nix
read(9, "v2hx2-python-2.7.17/lib/python2."..., 4096) = 4096
read(5, "7.17/lib/python2.7/re.pyt\7\0\0\0_pi"..., 4096) = 2196
read(4, "yankv2hx2-python-2.7.17/lib/pyth"..., 4096) = 486
read(4, "v2hx2-python-2.7.17/lib/python2."..., 65536) = 65536
read(5, "x2-python-2.7.17/lib/python2.7/c"..., 4096) = 143
read(9, "hon-2.7.17/lib/python2.7/hashlib"..., 4096) = 3272
read(11, "on-2.7.17/lib/python2.7/pickle.p"..., 4096) = 2904
stat("/lib64", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/lib/x86_64-linux-gnu", {st_mode=S_IFDIR|0755, st_size=16384, ...}) = 0
stat("/lib/i686-linux-gnu", 0x7ffc2f214d50) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 11
openat(AT_FDCWD, "/lib", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 11
openat(AT_FDCWD, "/lib/x86_64-linux-gnu", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 11
stat("/lib/x86_64-linux-gnu/libudev.so.1", {st_mode=S_IFREG|0644, st_size=149704, ...}) = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libudev.so.1", O_RDONLY|O_CLOEXEC) = 11
```

**Comment by mkg20001** [comment]
Ok, it only gets stranger from there

Without the system udev it fails to find ANY udev, not even the one in the store

```
root@rescue /lib/x86_64-linux-gnu # mkdir ub
root@rescue /lib/x86_64-linux-gnu # mv libudev.so.1* ub
root@rescue /lib/x86_64-linux-gnu # nixpart
Traceback (most recent call last):
  File "/nix/store/57k49zf2kwyaj96cnln1shqqcr33sc6q-nixpart-0.4.1/bin/.nixpart-wrapped", line 10, in <module>
    from nixkickstart import NixKickstart
  File "/nix/store/57k49zf2kwyaj96cnln1shqqcr33sc6q-nixpart-0.4.1/lib/python2.7/site-packages/nixkickstart.py", line 24, in <module>
    from blivet.deviceaction import *
  File "/nix/store/i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/__init__.py", line 68, in <module>
    from devices import *
  File "/nix/store/i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/devices.py", line 103, in <module>
    from devicelibs import mdraid
  File "/nix/store/i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/devicelibs/mdraid.py", line 25, in <module>
    from .. import util
  File "/nix/store/i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/util.py", line 7, in <module>
    from udev import udev_settle
  File "/nix/store/i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/udev.py", line 30, in <module>
    import pyudev
  File "/nix/store/i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/pyudev.py", line 38, in <module>
    raise ImportError, "No library named lib%s.so" % name
ImportError: No library named libudev.so
root@rescue /lib/x86_64-linux-gnu # cd /nix/store
root@rescue /nix/store # find -iname "*udev*"
./z2prq5kpkr7yxzhysnmv789czm37c66m-multipath-tools-0.4.9/lib/udev
./z2prq5kpkr7yxzhysnmv789czm37c66m-multipath-tools-0.4.9/etc/udev
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/share/zsh/site-functions/_udevadm
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/share/factory/etc/udev
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/share/factory/etc/udev/udev.conf
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/share/bash-completion/completions/udevadm
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/lib/udev
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/lib/udev/rules.d/50-udev-default.rules
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/lib/systemd/systemd-udevd
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/systemd-udevd.service
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/systemd-udevd-kernel.socket
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/systemd-udevd-control.socket
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/systemd-udev-trigger.service
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/systemd-udev-settle.service
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/sysinit.target.wants/systemd-udev-trigger.service
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/sysinit.target.wants/systemd-udevd.service
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/sockets.target.wants/systemd-udevd-control.socket
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/sockets.target.wants/systemd-udevd-kernel.socket
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/example/systemd/system/initrd-udevadm-cleanup-db.service
./v1fq42g0vlv7sh3jpfk4ga3lqfwdkg3b-systemd-243.3/bin/udevadm
./pch5i9l22qqwa9dn5hcfgc18wl0zh9ab-lvm2-2.02.106/lib/udev
./i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/pyudev.py
./i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/udev.py
./i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/pyudev.pyc
./i6kchll1w4qjca2cqrdnncdfiipk6wq7-blivet-0.17-1/lib/python2.7/site-packages/blivet/udev.pyc
./9d0hvhdj3pqn3cyi7ca254jzgfxrq9hv-lvm2-2.03.01/lib/udev
./1vsbkps97ar6b68l9xbvs5lk36b0s564-systemd-243.3-lib/lib/libudev.so.1.6.15
./1vsbkps97ar6b68l9xbvs5lk36b0s564-systemd-243.3-lib/lib/libudev.so.1
./1vsbkps97ar6b68l9xbvs5lk36b0s564-systemd-243.3-lib/lib/libudev.so
```

**Comment by aycanirican** [comment]
Could you please try this patch?

$ git diff
diff --git a/nix/hetzner-bootstrap.nix b/nix/hetzner-bootstrap.nix
index 035e6f9..def42a1 100644
--- a/nix/hetzner-bootstrap.nix
+++ b/nix/hetzner-bootstrap.nix
@@ -3,9 +3,7 @@ with import <nixpkgs> { system = "x86_64-linux"; };
 let
   pkgsNative = import <nixpkgs> {};

-  nixpart = python2Packages.nixpart0.override {
-    useNixUdev = false;
-  };
+  nixpart = python2Packages.nixpart0;

   generateConfig = (import <nixpkgs/nixos> {
     configuration = {};

Cheers,

**Comment by mkg20001** [comment]
Were do I apply this patch? The repo doesn't seem to have a nix/hetzner-bootstrap.nix

**Comment by mkg20001** [comment]
Ok, found it in https://github.com/nixos/nixops-hetzner

Still, the file already has that patch

```
with import <nixpkgs> { system = "x86_64-linux"; };

let
  pkgsNative = import <nixpkgs> {};

  nixpart = python2Packages.nixpart0;

```

**Comment by aycanirican** [comment]
Sorry, I thought that you were using pre-plugins branch. Please use pre-plugins branch and apply the patch. It should work since I was dealing with the same problem a few months ago.

**Comment by mkg20001** [comment]
Now I'm only getting better errors :rofl: 

```
maciej@mkg-pc:~/nixops$ nix-channel --update
unpacking channels...
maciej@mkg-pc:~/nixops$ nix-build release.nix -A build.x86_64-linux
error: getting attributes of path '/home/maciej/.nix-defexpr/channels/nixpkgs/nixos/doc/manual/options-to-docbook.xsl': No such file or directory
(use '--show-trace' to show detailed location information)
```

**Comment by domenkozar** [comment]
This is fixed in nixpkgs master and 19.09, you'll have to update your nixpkgs.

**Comment by domenkozar** [comment]
Hmm, I thought it is. Need to submit a PR.

**Comment by domenkozar** [comment]
Pushed https://github.com/NixOS/nixpkgs/commit/c49ca3e5056052d43edda1d668fb45ac05676001

**Comment by paluh** [comment]
Sorry for a basic/stupid question - I'm just starting to use `NixOps` and I'm not an `Nix` expert. How can I use this patch from `19.09` channel (I don't want to switch to `master` - should I?). Can I somehow override `blivet.nix` in my hetzner deployment?

**Comment by mkg20001** [comment]
You can patch the repo and build the patched version using the steps as described on the README, then execute that binary instead

**Comment by paluh** [comment]
@mkg20001 Thanks for suggestion!

Unfortunately I'm not sure if I follow. Which repo should I patch? I'm trying to start using `nixops` on `19.09` (pre plugin nixops version) - as a newbie I don't want to try development `nixops` version.

What I wanted really is to get some hint how to write `shell.nix` which patches `blivet.nix` on `19.09` so deployment with `nixops` to hetzner will work. Is it possible?

P.S.
Please excuse my newbie questions but this is my first attempt to migrate some servers from `ansible` to `nixops` and I've really hard time trying the basics. After a few hours of banging my had against `Anauthorized` exception I was able to find that I should use [deployment.hetzner.createSubAccount = false](https://github.com/aszlig/hetzner/issues/34). Now I'm hitting a problem which again makes deployment of `trivial` example from manual impossible...

**Comment by mkg20001** [comment]
Works now
