### ISSUE TITLE
nixops deploy to DigitalOcean - Cloning builder process: Operation not permitted

### ISSUE THREAD

**Issue by koslambrou** [NixOS/nixops#1249]
Here's my `web-docean.nix` following the instructions in the manual for creating a Droplet in DigitalOcean with `nixops`:
```
{
  resources.sshKeyPairs.ssh-key = {};

  webserver = { pkgs, ... }: {
    services.nginx.enable = true;
    services.openssh.enable = true;

    deployment.targetEnv = "digitalOcean";
    deployment.digitalOcean.enableIpv6 = false;
    deployment.digitalOcean.region = "nyc3";
    deployment.digitalOcean.size = "s-1vcpu-1gb";
    deployment.digitalOcean.authToken = "mytoken";
  };
}
```

Afterwards, I deployed the configuration with:
```
nixops create web-docean.nix -d web
nixops deploy -d web
```

The deployment failed with a "Cloning builder process: Operation not permitted"
```
building all machine configurations...
trace: warning: The option `ip4' defined in `/run/user/1000/nixops-tmpqM2XCS/physical.nix' has been renamed to `ipv4.addresses'.
these derivations will be built:
  /nix/store/08y026g00azzzcn56n5j1pnhym64pc0j-mounts.sh.drv
  /nix/store/3j098naf641j838wr8h47grj5ciw5ybk-nixos.conf.drv
  /nix/store/0bj6mqpbcp2vlzk8yav6hgbyq9krxbz9-unit-systemd-modules-load.service.drv
  /nix/store/0dnkzx81lgjgj2rywwb883dvbpyn0b9f-unit-script-network-addresses-ens3-start.drv
  /nix/store/0lz522cf7bnpm2vj613cd9k550szznki-etc-hosts.drv
  /nix/store/0m8x6x4kgm4972anshszfpx6s06ip6sm-extra-udev-rules.drv
  /nix/store/0wg87ayay0n9yw8dxajw434ndalpdb6b-unit-user-.service.drv
  /nix/store/0xrr47dfy9pj2nvn577s34m2wh3bxc4x-unit-serial-getty-.service.drv
  /nix/store/70778fzgv2yqrcw7pwmj1l6s74h2143g-nginx.conf.drv
  /nix/store/10bkg7y14sd9rk9f7isvwqqrz4dk9g5l-unit-script-nginx-pre-start.drv
  /nix/store/1dfxzyfs2rpmgc32krr7byiyyhfjj0nl-unit-systemd-random-seed.service.drv
  /nix/store/hzrwwwv56s9hg64m6c7x16mjx0vxxl9i-local-cmds.drv
  /nix/store/1h8r33zby7jw9z72hjx54li9kf1jg20p-stage-2-init.sh.drv
  /nix/store/1wh8dz9qkzkf53js38lpxy65rfl98wkx-ipv6-privacy-extensions.rules.drv
  /nix/store/1x0bf1j5iv7xibccwqz7g5p8f7zqw27k-unit-save-hwclock.service.drv
  /nix/store/1zfjmpsfygf37aks0mcafkpsilywkn88-unit-systemd-timedated.service.drv
  /nix/store/22fpsiq3rsyy43x9kx01fygrq4a1bhmf-udev-path.drv
  /nix/store/5vpxnz358y5gqcbyg5kn4ggcp11jvijw-pam-environment.drv
  /nix/store/25qzfch6ckqcbbd5n89ha55kxf9ln6vh-polkit-1.pam.drv
  /nix/store/2cj1gj6cx32bxw3rgp4y7br186rk6fji-passwd.pam.drv
  /nix/store/2d1nsyj0c5fip1w9dn6lkm8hd53dafwk-install-grub.pl.drv
  /nix/store/2fdb61pd1w10qlh4qqbihis3adkvg132-unit-script-sshd-pre-start.drv
  /nix/store/2gxs4z2nl7fyv45a5cwiyv7py18pr022-etc-shells.drv
  /nix/store/2hwx4wrlymdc9p8c87bn8zxaiv37qajy-users-groups.json.drv
  /nix/store/2ic8z6cskyz1n7js88hg901jq71s9awh-unit-nix-optimise.service.drv
  /nix/store/2j74gmx26cxzz23mdqqyzkqq56ld1cd7-unit-user-runtime-dir-.service.drv
  /nix/store/75ldk0mplp3cxgy7y86id96nhw4sinbg-node_nix-sandbox-0.0.0.drv
  /nix/store/2xm4gv1gx1hqbl6c4nnjrlg4czzdw1ag-unit-nix-sandbox.service.drv
  /nix/store/c8cr6gv184ljcxjbaabq96n6i8ab9a9b-unit-script-nixos-activation-start.drv
  /nix/store/3dkgyz7gc8dhhdix1dkkdk547aw4b1aa-unit-nixos-activation.service.drv
  /nix/store/rmk1bmrrp4w3wj10ijcjckijij7rhvfk-etc-timesyncd.conf.drv
  /nix/store/3kdp2bsyy9nndl2fg1d6drgcf33rvazm-unit-systemd-timesyncd.service.drv
  /nix/store/3lxffl2ralfr3zs4vbr8ragjvwhssfmm-etc-nscd.conf.drv
  /nix/store/3ny23iglq90dbbms6gap2d950vwq407a-userdel.pam.drv
  /nix/store/3w730ihk7pyx55z67rinzhm1zqnnzbk5-unit-keys.target.drv
  /nix/store/4f33sd3nv2sbsa1v7p867jq28ch93wn8-unit-nix-daemon.socket.drv
  /nix/store/5g1g2zqpcgk6hhg3bqlfrx7gf838ghp0-etc-nanorc.drv
  /nix/store/5lm4bx14l9bnx5bhq6ik4b80844023qb-useradd.pam.drv
  /nix/store/r8h580radwyxz2l54zr8x5gq8g5ijy9x-etc-nsswitch.conf.drv
  /nix/store/5zn728cq8ywkx6r6sgk1x0lilsmyzmig-unit-nscd.service.drv
  /nix/store/60m2dp2gblgypmlmvdgz38xqpfr6j894-etc-sleep.conf.drv
  /nix/store/az506g8fn15gvl6bp1z6cyz5yr9xmryf-unit-graphical-session.target.drv
  /nix/store/6r4bkh650z9s8b6myjfq3s7j1z0cashp-nixos-generate-config.drv
  /nix/store/yf6j2zn11n9ajas9dz747lwj9jdfa9nx-nixos-enter.drv
  /nix/store/g58hp79dlxvwqarqvi8mkcpscxzgn73j-nixos-install.drv
  /nix/store/ilk10kdqv6abpc8hhdqq32i9xa31ds8h-nixos-option.drv
  /nix/store/mv5qzi0q2b32kixp2lxvkqwh14i3n7zz-nixos-version.drv
  /nix/store/nds121h8489a16xzfvfcwgiszspm6nqj-nixos-container.drv
  /nix/store/ql3jpsjxiyxda145v0bfadk8241n2phh-command-not-found.drv
  /nix/store/rrmrqbw96hczy47lg70zg4j59z3qgmsj-nixos-rebuild.drv
  /nix/store/v92brpw76dzffkc0ay3qr6s31sqhax5j-nixos-build-vms.drv
  /nix/store/xh70w7kxvi2hf9qnnqsxvahrny10cmnr-nixos-help.drv
  /nix/store/lglxmrhdynq4a6q07fd8jgykd7rvycps-system-path.drv
  /nix/store/s65jmh9p8r185dkf1y5nihm49zflwsx0-dbus-catalog.xml.drv
  /nix/store/ilng3ichl924hz28fgg5vp7ynvrw4dhv-dbus-1.drv
  /nix/store/mf5cdim0amw8imrlbd8rqgfslk5dr876-unit-dbus.service.drv
  /nix/store/qvnivnvc2v0xy3ialhfi9rx5diwbh7h6-unit-dbus.socket.drv
  /nix/store/62c076nqma3y965yirv61r091kifar3q-user-units.drv
  /nix/store/65jq8jz3p94qr6ivhbpyhzx42wsdqg3h-vlock.pam.drv
  /nix/store/6fkffizk0018b5j6zbfp9kaayk0dzywr-other.pam.drv
  /nix/store/6j1my2wnp603s14ypgd9syjclybny73d-cups.pam.drv
  /nix/store/6lxnvv3n5vk0h3jc74hwibdqc4znv9ya-issue.drv
  /nix/store/6m3bzykva62dankiwgi65szqby82fg3k-unit-kubelet.target.drv
  /nix/store/6y0l8mqbz84qkvg47ayg4k5s2g9ql027-unit-systemd-binfmt.service.drv
  /nix/store/6zyx34aiccv4qbws5jn0safk9qss4vdp-groupdel.pam.drv
  /nix/store/721x4krcs6yvxr7j9d9rxl75nckb56j0-unit-systemd-backlight-.service.drv
  /nix/store/7d9fahf71snqkpkvpxrbp027qs4x5pxz-root-authorized_keys.drv
  /nix/store/pby63lagxg98j5pjln0xgcldsh8j1491-unit-script-post-resume-start.drv
  /nix/store/7kgwijp5m7qw3infiahpzj64jx26vvap-unit-post-resume.service.drv
  /nix/store/7q3cwlmk9b4fhmb4ihjip8a7xjpijnqm-i3lock.pam.drv
  /nix/store/7qgms6n4jqad297dyzz08f46m2dqmfqd-groupadd.pam.drv
  /nix/store/a7qim3g91xyglskwsbchid3lnx7pdhsi-set-environment.drv
  /nix/store/8za48w9kw6p1dksk7qah636gl0pfxqhp-extra-hwdb-file.drv
  /nix/store/ls4635hkkymx18s0rfp9acyjjqadfd9i-ipv6-privacy-extensions.rules.drv
  /nix/store/a9xp392cjcb5sj8pphpgynial2znz2sb-hwdb.bin.drv
  /nix/store/adc84jv695dc628jrbczzpj41cfplbfz-etc-nixos.conf.drv
  /nix/store/ap27vi9xrcgrypg1vqyqnrcq72q2ignq-xlock.pam.drv
  /nix/store/asjnrhbw9n3kccmyki8a9nrr0akn72hd-etc-host.conf.drv
  /nix/store/b8d2vfk7ld20sl4db4rz92kylf65ykjm-systemd-user.pam.drv
  /nix/store/c5xy33rfzw155svvz7qzqm3xcxry0hc5-xscreensaver.pam.drv
  /nix/store/c61rvrpdsmfdvqxdqp6p3iyq5kcbiilw-etc-journald.conf.drv
  /nix/store/cvaq4h98n4by289nnd7fnpvrng606vig-etc-subgid.drv
  /nix/store/dqj52xvjgb832lxxaxk6b1g9ahhq933w-groupmod.pam.drv
  /nix/store/dwzdxgklfx4vfjs2syfb72679d7dgpvn-etc-user.conf.drv
  /nix/store/dyxlpmqwyi75rx1708s9386wvyy9qf6p-i3lock-color.pam.drv
  /nix/store/9nb7spbr2c6a9q3pl972gjvknqs2cmys-firmware.drv
  /nix/store/fjq7jbiy21p7qd5pymlyr70c2v4xjnk1-etc-nixos.conf.drv
  /nix/store/hy5q9qc9wfbkvqzinjzl7sxr8r1vnaxv-fontconfig-etc.drv
  /nix/store/i7a69mj2v01w0vsarywn3zrfs71pzlj3-runuser.pam.drv
  /nix/store/jcd5fb9n1h8iay4z0sd5qdh7j88rm33b-groupmems.pam.drv
  /nix/store/jd5c283hma9s0kky7k0jylaln1nj69xw-chpasswd.pam.drv
  /nix/store/jlqmwjfbd7sp3f7pyp4819s7akalsys4-screen.pam.drv
  /nix/store/laghs90p7h7cb60q10jhdv5s1xzz4vqf-login.defs.drv
  /nix/store/liny12qz24j0m851r03vxmfgwsykjf72-chfn.pam.drv
  /nix/store/lirfp070f9lz10bj3zz2ncmmfn77lhf0-sshd.pam.drv
  /nix/store/lpxskcpqd125mrcxydgxigb50znplnny-etc-ssh_known_hosts.drv
  /nix/store/m0949yvv04markkmv1s6gsaq0fakyd95-smb-dummy.conf.drv
  /nix/store/m9da7g8ipyi1wpbg1bwh4ki5nvfp77lg-runuser-l.pam.drv
  /nix/store/mhlisf91rannnfmcpkyywpv9rv03rb4q-etc-ssh_config.drv
  /nix/store/mrdjmzfp0z7p4i8h8jvnj4sa4w3dn7fh-etc-nixos.conf.drv
  /nix/store/mrk2n37x9mqdmppfjbqgsfd3sya4ixs1-etc-profile.drv
  /nix/store/n4vk5dg471xva310smqxkrhkrwk2f85g-login.pam.drv
  /nix/store/nxmavc61h8pmwscb014wr901qc8zsjxi-etc-resolvconf.conf.drv
  /nix/store/p1kx9nb5jvcby5j6snpyx30bw41gp7zg-udev-rules.drv
  /nix/store/pgl0b8bj7x4inf9lh9zlq0698733qrc6-ftp.pam.drv
  /nix/store/ppnd4cdf36mczc7nhh5smmbpnj40jp0h-client.conf.drv
  /nix/store/ppp214brzzj1810jj3d1fv3vals1agr4-etc-bashrc.drv
  /nix/store/pxppkjc2xjkc19i5mjngia2mgbb7rdkg-etc-os-release.drv
  /nix/store/q1w5qnk7sym2n2vjd28n1cvn75n6r5fs-chsh.pam.drv
  /nix/store/ag8gbmhqxsmhx1y53wjcdczjp5nnl6w7-dhcpcd.conf.drv
  /nix/store/7q3zhi2s4mj1h7gd83bmgfrnfj094m55-unit-dhcpcd.service.drv
  /nix/store/87fifjbcdq0p1kifhn189r501ck786x3-unit-systemd-user-sessions.service.drv
  /nix/store/8ab6f8id9g5xxq68dkw03wh6wbv3jfwa-unit-systemd-logind.service.drv
  /nix/store/8di5dyp0xnppq1n8gfvx3178rg84f5q3-unit-polkit.service.drv
  /nix/store/xjna18wb7516s5dg1qzw4rwnm30x0xvg-unit-script-prepare-kexec-start.drv
  /nix/store/b0qrvfhkhwfg4b33cwnmxp098m0n57qi-unit-prepare-kexec.service.drv
  /nix/store/b8nqd4hsd7m0v067x17g9wr88bkjrq42-unit-multi-user.target.drv
  /nix/store/czb4p160xa5khnl9g6yndz5pzik71qcj-unit-mdmon-.service.drv
  /nix/store/drnswc2hgyyii9da98kjwq0bf182p9w3-unit-local-fs.target.drv
  /nix/store/falw9vk2q7wn25ssn2npi8bc2m4abwsj-unit-systemd-update-utmp.service.drv
  /nix/store/fyrf4ajdg6ifd6xf20zlpriaaq52s7a5-unit-getty-.service.drv
  /nix/store/g4abx0yd748znk5789lrp7fidrk3yjmm-unit-console-getty.service-disabled.drv
  /nix/store/gcvvip4rji724hpi40b1iyb3s8xhazsw-unit-encrypted-links.target.drv
  /nix/store/hf8d7acl3j8if96m6j852yva7cq5xrfx-unit-mdadm-shutdown.service.drv
  /nix/store/hkhs1virs7pk93rvvgrk8xjfpzby33d7-unit-dbus.service.drv
  /nix/store/i8nd3bcp3lga6l12x0gkf4g16cjf5c9i-unit-script-nix-gc-start.drv
  /nix/store/hm57d690giypc6q85z538nxnkvmh87gg-unit-nix-gc.service.drv
  /nix/store/rnksl77qadwqxldbvg674gca7lqn6fwp-unit-script-network-addresses-ens3-pre-stop.drv
  /nix/store/hxli2lgimp8kgclabjr883qb4pmcifjb-unit-network-addresses-ens3.service.drv
  /nix/store/nigvz3zacsbb3hdj6vdz5g44hwc24lzh-unit-script-network-local-commands-start.drv
  /nix/store/ikb8l0anjd9pfr6c68pr350zf2i9j9ki-unit-network-local-commands.service.drv
  /nix/store/iv0yp561cgv3sz5d2scyrqdpqi0fk73c-unit-systemd-journal-gatewayd.socket.drv
  /nix/store/jd9xw8skq6x3x9ijq1d0xjrxdf4ygkfl-unit-fs.target.drv
  /nix/store/cl8d4j63gcz81prw5hs5zrv3pqhdi3h4-firewall-start.drv
  /nix/store/ib74bxqc0bjb732pfa1yzxnf2sdm7s9r-firewall-stop.drv
  /nix/store/xddpmc523z36s70lay61dmz8pa3075mi-firewall-reload.drv
  /nix/store/js84prssmyq1a81yx18x794js3n70d7b-unit-firewall.service.drv
  /nix/store/lgqpxw2grf0mlr8ff5gfp7phjhl6d55i-audit-disable.drv
  /nix/store/wrd4aw6k4609lnbkc9qjkp72n1x1jijh-audit-stop.drv
  /nix/store/ka2i7g9j0r8w23v2w1xc4wjhq5p4b3rn-unit-audit.service.drv
  /nix/store/kqgypqiyfzrq87b0rw8radzjqkr0b5l2-unit-nginx.service.drv
  /nix/store/l63s7cynysdlh2krnbixg9iqdy4d2xi8-unit-mdadm-grow-continue-.service.drv
  /nix/store/llrhs36jj33m333snrc8yxcgb78wqzn6-unit-systemd-udevd.service.drv
  /nix/store/yq665klx4rkxnlh1dflq3cxqil1idbbg-unit-script-network-setup-start.drv
  /nix/store/mrgj4w90jmny1g9yg5nvxbqj70x5pxbq-unit-network-setup.service.drv
  /nix/store/r9gwmd06jw7s9ylhb06iqrsrc3dw9g7x-kbd-env.drv
  /nix/store/xgppsgkhh9mx9hvni5srh30wm1ip5iz7-vconsole.conf.drv
  /nix/store/ms4av2rmanq9xd5k4rm0n0ivdvjg0l1d-unit-systemd-vconsole-setup.service.drv
  /nix/store/mz4yy34f1x9kh3kkwzwchw8l2ql3mm0z-unit-resolvconf.service.drv
  /nix/store/blzbmcylnda60kh0x1j73qjqhlbhibcy-unit-script-pre-sleep-start.drv
  /nix/store/ndv86775959dddkibcbz79ilra01g0r6-unit-pre-sleep.service.drv
  /nix/store/p613y9xn9l1p12zjrn7ar79hdg2wvyj4-unit-kube-node-online.target.drv
  /nix/store/yfa1dlr8n269l7k5gsr9qm9ggdraz95h-unit-script-network-link-ens3-start.drv
  /nix/store/q42xnx5317riwdxwcjhxz3cblcp07sjr-unit-network-link-ens3.service.drv
  /nix/store/r1h539f2hga1k71cq07pd5d6wvy0s07d-unit-systemd-journal-flush.service.drv
  /nix/store/r57fabdrvq04bskcv3gaw6rasb5xylrn-unit-nix-daemon.service.drv
  /nix/store/rvk3q3shmlhqfnfkvi93mvy85ycsywg7-unit-post-resume.target.drv
  /nix/store/s4bals9dk4iig6wkmlzdz84p644q0p4m-unit-remote-fs.target.drv
  /nix/store/s5y2iv3vkfq7za4vvknd8ccrzd7h7vpr-unit-systemd-sysctl.service.drv
  /nix/store/sjw61g73sxm6kl5jp9wqiv2d0shsmr1n-unit-systemd-remount-fs.service.drv
  /nix/store/sm829ca4gm25j6wsfp2mpird5y24y9yb-unit-network-online.target.drv
  /nix/store/v0lzw608r3ja9xnp4cjmq59v0fmf14fv-unit-container-getty-.service.drv
  /nix/store/w1i8nh3gfh09s6pw6hcarf5bq21iwynn-unit-systemd-udev-settle.service.drv
  /nix/store/x2sr60k74bzcmg1icynryswvlyzvjznx-unit-systemd-fsck-.service.drv
  /nix/store/xa99kahb6n8pj07q65cp7pn2rgjk64dx-unit-nixops-keys.service-disabled.drv
  /nix/store/y6gib7lp5a8n2j5hbjpc8v3a045ywq3z-unit-sshd.service.drv
  /nix/store/8m4fl08f9m7zw1h5g21z179xnmybcc70-unit-script-container_-post-start.drv
  /nix/store/ilv54bgfb5ddgxpw42f5psh0cdg8w1ij-container-init.drv
  /nix/store/cxyfychwnkj05rlfw5mh2823d6ci2gag-unit-script-container_-start.drv
  /nix/store/gqv9nj62zwqibfwp95ysmldv7h32104z-unit-script-container_-pre-stop.drv
  /nix/store/n9x9akns0n20930x2fqpirjlhk1hnz4v-reload-container.drv
  /nix/store/pnna83dmc64lgpyi30g922blc7gv8hmn-unit-script-container_-pre-start.drv
  /nix/store/y6gjmjffajmf7vshf9bcrxfdmw6iy3i7-unit-container-.service.drv
  /nix/store/yi9gy4n9w15rrw47y5islm97s95yhyik-unit-network-interfaces.target.drv
  /nix/store/zamkczzvcvmm3jkj0wgsizg457caswnm-unit-systemd-journald.service.drv
  /nix/store/qrdpac0lcc2rmry5ddc4486j43ljw54b-system-units.drv
  /nix/store/r2i6ms8n9pq3q14x8diaddlx5c6g19fk-locale.conf.drv
  /nix/store/r8qq9v74vv53268g48xi8vh386iijs2s-etc-logind.conf.drv
  /nix/store/s2kslbkr8r61wnxi6bipf9p9j63v561v-etc-system.conf.drv
  /nix/store/sy9xrlffwnw4ckibzrdz55vwni01d6iz-usermod.pam.drv
  /nix/store/vjp4m8plp46vd2qmcmj6wk98wjv6x559-etc-hostname.drv
  /nix/store/wfagrd35wcwdnvp5fcjf71q90x34ll8n-dhcpcd.exit-hook.drv
  /nix/store/whlsgdvx0jxd03lva0hdcsp7mw8w4cmx-sudo.pam.drv
  /nix/store/xcq6kx9zkhxxrpasglasd4s91qrx08q0-etc-fstab.drv
  /nix/store/z07cway5fqxicvyg2i06h11y1bkr7rg8-etc-10-nixos.rules.drv
  /nix/store/z1gcnlp28gvnkzxsv7bik8lcg2i0bkh7-etc-subuid.drv
  /nix/store/z22vi2hvq6z7frjkwwkd8a46igpx1p37-su.pam.drv
  /nix/store/zvpzk5zaajghigi5ywijy6kjb7rb3mpv-useradd.drv
  /nix/store/7l6zssx6i1pq7gc1ias2hzy247w4mi89-etc.drv
  /nix/store/c2h0m9ss9kyhsj0zk3w93jm5a0vn0lg0-append-initrd-secrets.drv
  /nix/store/ibdz2z6gv7wj8y6cigix62qqd77l2zcd-grub-config.xml.drv
  /nix/store/ciknq0i3x61dk01k0ag687gyxigrgm33-install-grub.sh.drv
  /nix/store/k9yq0dxsd1kzas181f2fyqvpz7zxw4am-kernel-modules.drv
  /nix/store/n0ix3drx5ak4aqsj3s4a09lgrmij70ra-setup-keys.sh.drv
  /nix/store/w1hi4nahw2dyfj9ij9hvi381b3bql0hr-mdadm.conf.drv
  /nix/store/z4i3yap0z702db5zfmbb45af8xbjfsz8-initrd-fsinfo.drv
  /nix/store/w5f61v2gmcxc202slvv6p8z3yc4kyjwv-stage-1-init.sh.drv
  /nix/store/qahk8f6gz2x0yjgh8hl3g5yfjzgs3pjj-initrd-linux-4.19.60.drv
  /nix/store/gj3w5szm0h4a9238jvmhmgxifqknafvl-nixos-system-webserver-19.09pre186574.88d9f776091.drv
  /nix/store/rks9r2748cikjaq16mivkbzidqyjvrg9-nixops-machines.drv
these paths will be fetched (2.83 MiB download, 9.56 MiB unpacked):
  /nix/store/1nn4bf0hsgl55wgng1azmvqp6wip2aiw-linux-4.19.60-modules-shrunk
  /nix/store/23qyccbp1nsh0lk3j353hdf1nvl5mv2i-btrfs-progs-5.1.1
  /nix/store/hyhf7n5fr6zszrfc649wfwxz0yvfy78h-sshd.conf-validated
  /nix/store/nk89xf35s05jd5czrg35wmhixslq8jbx-udisks-2.8.2
error: cloning builder process: Operation not permitted
error: unable to start build process
Traceback (most recent call last):
  File "/nix/store/gc2l5q4vgc9x56sc939i3bc9hf9r88hs-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/gc2l5q4vgc9x56sc939i3bc9hf9r88hs-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/gc2l5q4vgc9x56sc939i3bc9hf9r88hs-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/gc2l5q4vgc9x56sc939i3bc9hf9r88hs-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/gc2l5q4vgc9x56sc939i3bc9hf9r88hs-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/gc2l5q4vgc9x56sc939i3bc9hf9r88hs-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1003, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/gc2l5q4vgc9x56sc939i3bc9hf9r88hs-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 671, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
```

How can I solve this ?

**Comment by AmineChikhaoui** [comment]
I think this means you can't build derivations with sandboxing enabled in general.

**Comment by koslambrou** [comment]
After changing the deployment name from `webserver` to something else and redeploying, it solved the issue. I don't understand why though.
