### ISSUE TITLE
sqlite3.ProgrammingError: Cannot operate on a closed database.

### ISSUE THREAD

**Issue by manveru** [NixOS/nixops#1316]
Given this code:

```
let
  sources = {
    nixpkgs = fetchTarball {
      url = https://github.com/nixos/nixpkgs-channels/archive/10100a97c8964e82b30f180fda41ade8e6f69e41.tar.gz;
      sha256 = "011f36kr3c1ria7rag7px26bh73d1b0xpqadd149bysf4hg17rln";
    };
    nixops = fetchTarball {
      url = https://github.com/input-output-hk/nixops/archive/9d343be645b296228a557868d431e14e7c64e73e.tar.gz;
      sha256 = "052v16mh4km8fdcmmkl6k782wsn7fmf55bi018s8n46d18rzbn9y";
    };
    nixops-aws = fetchTarball {
      url = https://github.com/input-output-hk/nixops-aws/archive/ce731a74f774c6701964377132c7e46b166f2a48.tar.gz;
      sha256 = "0q3pdbrkd3qzv24s2iyy456apcxq6flra720lawhlvbbfqyblhgj";
    };
  };
  pkgs = import sources.nixpkgs {};
  nixops = import sources.nixops { inherit pkgs; };
in nixops.withPlugins (ps: [ (ps.callPackage sources.nixops-aws { inherit pkgs; }) ])
```

`nixops info -d foo` errors with:

```
Traceback (most recent call last):
  File "/nix/store/nrm0rngcf44zkrp46nvckhs9g9bg41ch-python3.7-nixops-1.8.0/bin/.nixops-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/cl38jrlsn06k255z0jvcv47pxk0lhcjy-python3-3.7.7-env/lib/python3.7/site-packages/nixops/__main__.py", line 634, in main
    args.op(args)
  File "/nix/store/cl38jrlsn06k255z0jvcv47pxk0lhcjy-python3-3.7.7-env/lib/python3.7/site-packages/nixops/script_defs.py", line 345, in op_info
    print("Network name:", depl.name or "(none)")
  File "/nix/store/cl38jrlsn06k255z0jvcv47pxk0lhcjy-python3-3.7.7-env/lib/python3.7/site-packages/nixops/util.py", line 305, in get
    s: Any = self._get_attr(name, default)
  File "/nix/store/cl38jrlsn06k255z0jvcv47pxk0lhcjy-python3-3.7.7-env/lib/python3.7/site-packages/nixops/deployment.py", line 237, in _get_attr
    c = self._db.cursor()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by grahamc** [comment]
It turned out the issue was in a rebase:

```
16:13 <gchristensen> manveru: what was up with the indentation error, and can you share some more info? :)
16:13 <manveru> https://github.com/input-output-hk/nixops/commit/ff7c5fea225425161188b54cf2b86da8a955e0e0
16:13 <manveru> it was our rebase gone wrong
16:14 <manveru> there are two `depl` variables, the `with` statement shadows it
16:14 <gchristensen> oh so the issue was in a rebase?
16:14 <gchristensen> and not in master?
16:14 <manveru> jup
16:14 <manveru> i'll close the issue
```

thanks!
