### ISSUE TITLE
Adding output in shell initialization breaks nixops deployment

### ISSUE THREAD

**Issue by Avaq** [NixOS/nixops#1335]
### Steps to reproduce

1. Include the following configuration (`shellInit` also works) in a nixops machine:

    ```nix
    {
      programs.bash.loginShellInit = lib.mkAfter ''
        echo hello world
      '';
    }
    ```

2. Deploy the machine (in my case the machine is localhost). Notice already how our output is being echoed:

    ```console
    $ nixops deploy --include machine
    machine> copying closure...
    home> closures copied successfully
    machine> activating the configuration...
    machine> setting up /etc...
    machine> reloading user units for root...
    machine> hello world
    machine> reloading user units for avaq...
    machine> hello world
    machine> setting up tmpfiles
    machine> activation finished successfully
    ```

3. Try to deploy again, maybe just to revert the mess we just made.

    ```console
    $ $ nixops deploy --include machine 
    machine> hello world
    building all machine configurations...
    machine> copying closure...
    machine> error: serialised integer 8031924123371070824 is too large for type 'j'
    Traceback (most recent call last):
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
        args.op()
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
        max_concurrent_activate=args.max_concurrent_activate)
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
        self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
        f()
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
        self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1010, in _deploy
        max_concurrent_copy=max_concurrent_copy)
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 694, in copy_closures
        tasks=self.active.itervalues(), worker_fun=worker)
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
        result_queue.put((worker_fun(t), None, t.name))
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 690, in worker
        m.copy_closure_to(m.new_toplevel)
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 367, in copy_closure_to
        env=env)
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 324, in _logged_exec
        return nixops.util.logged_exec(command, self.logger, **kwargs)
      File "/nix/store/fgwchwdvf6xqysf26knwrryw4pwzpkmf-nixops-1.7/lib/python2.7/site-packages/nixops/util.py", line 152, in logged_exec
        raise CommandFailed(err, res)
    nixops.util.CommandFailed: command ‘['nix-copy-closure', '--to', 'root@127.0.0.1', u'/nix/store/0gzw9lbzwa7f56igxjxm30fm9cchrs0n-nixos-system-monkey-bridge-20.03.1619.ab3adfe1c76']’ failed on machine ‘machine’ (exit code 1)
    ```

### Expected result

The deployment keeps working even with the extra output.

### Actual result

As shown above, the deployment fails. A rollback also fails. I was forced to reboot the machine into the previous generation.

I'm not sure if I'm just doing something that goes against all reason, or whether this is an actual bug. But I could find no mention of it in this bug tracker, so even if this issue is immediately closed, it should serve to repel future adventurists.

**Comment by Avaq** [comment]
Hm, maybe it also adds this output to all subshells being spawned? In that case it would make sense that it breaks a bunch of stuff.

**Comment by cleverca22** [comment]
it will likely break `scp` and `nix-copy-closure` as well

**Comment by Avaq** [comment]
I suppose it's out of scope for nixops, and likely any other nix project then, right? I essentially just did something silly.

**Comment by cleverca22** [comment]
yeah, about all else i can say, is that you can do a normal `nixos-rebuild rollback` over ssh, no need to reboot in this situation

**Comment by Avaq** [comment]
Ah. Good tip! I'll close this then.
