### ISSUE TITLE
`nixops rollback` errors with `Bug: Deployment.definitions is None.`

### ISSUE THREAD

**Issue by cole-h** [NixOS/nixops#1354]
This happens while running off master at 68aa76845573a8e6613286a730f0a2c9e394af97.

What I did to trigger this was the following:
1. enable rollback with `network.enableRollback = true;`
2. deploy to get that change "out there"
3. make a trivial change (like adding or removing a package) and deploy again
4. try to `nixops rollback 1`
5. experience the following error:

```
$ nixops rollback 3
switching from generation 4 to 3
scadrial> copying closure...
cosmere> closures copied successfully
scadrial> error: Traceback (most recent call last):
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 901, in worker
    set_profile()
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 877, in set_profile
    defn = self._machine_definition_for_required(m.name)
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 181, in _machine_definition_for_required
    defn = self._definition_for_required(name)
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 173, in _definition_for_required
    defn = self._definition_for(name)
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 166, in _definition_for
    definitions = self._definitions()
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 160, in _definitions
    raise Exception("Bug: Deployment.definitions is None.")
Exception: Bug: Deployment.definitions is None.

Traceback (most recent call last):
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/bin/.nixops-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/__main__.py", line 705, in main
    args.op(args)
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/script_defs.py", line 942, in op_rollback
    sync=not args.no_sync,
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 1457, in rollback
    self._rollback(**kwargs)
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 1452, in _rollback
    max_concurrent_activate=max_concurrent_activate,
  File "/nix/store/j3ydqai7s5nhr37kx6743v9409a48418-nixops-1.8.0/lib/python3.7/site-packages/nixops/deployment.py", line 971, in activate_configs
    ", ".join(["‘{0}’".format(x) for x in failed]),
Exception: activation of 1 of 1 machines failed (namely on ‘scadrial’)
```

Strangely enough, `nixops list-generations` does show that the `(current)` generation is indeed the one specified to roll back to, but the changes don't take place.

My `deployment.nix` can be found here: https://github.com/cole-h/nixos-config/blob/nixos/deployment.nix

**Comment by PAI5REECHO** [comment]
So have rollbacks just never worked?

**Comment by cole-h** [comment]
I haven't used nixops in quite a while, and I no longer care.
