### ISSUE TITLE
`nixops mount` fails with error "no such file or directory"

### ISSUE THREAD

**Issue by JustinLovinger** [NixOS/nixops#1361]
Running `nixops mount`, like `nixops mount static-site-server ~/mnt` fails with

```
Traceback (most recent call last):
  File "/nix/store/0xx0rxr7gw5bj4qz5h6rbdxrp4r5mb5s-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/0xx0rxr7gw5bj4qz5h6rbdxrp4r5mb5s-nixops-1.7/bin/..nixops-wrapped-wrapped", line 632, in op_mount
    + new_flags)
  File "/nix/store/0yz15vp6xvaixrkls7y85r65d95jc0m4-python-2.7.17/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/0yz15vp6xvaixrkls7y85r65d95jc0m4-python-2.7.17/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/nix/store/0yz15vp6xvaixrkls7y85r65d95jc0m4-python-2.7.17/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The mountpoint exists. I've tried variants like `nixops mount static-site-server /mnt` and `nixops mount "root@static-site-server:/" "/home/usr/mnt"`, but they all fail with the same error.

**Comment by adisbladis** [comment]
I have a feeling you're missing `sshfs` which for some reason is not wrapped by NixOps.
Could you try `nix-shell -p sshfs --run "nixops mount ..."`?

**Comment by JustinLovinger** [comment]
> I have a feeling you're missing `sshfs` which for some reason is not wrapped by NixOps.
> Could you try `nix-shell -p sshfs --run "nixops mount ..."`?

That fixed it. Looks like the NixOps package is missing the sshfs dependency.
