### ISSUE TITLE
Failure to deploy if remote machine has no internet connectivity

### ISSUE THREAD

**Issue by blitz** [NixOS/nixops#1373]
I'm trying to use nixops to deploy to a machine that has (intentionally) no connection to the internet. This would be a nice fit, because nixops builds everything local anyhow.

The problem I'm hitting is that the target tries to use substitutes and this makes the deployment fail. See below. The problem seems to be the `--use-substitutes` parameter in the call to `nix-copy-closure`. Is there a way to turn this behavior off?

```
targetHost> copying closure...
targetHost> warning: unable to download 'https://cache.nixos.org/0xhjv5m80j0a3dik7kgf9s3qbsxizncj.narinfo': Couldn't resolve host name (6); retrying in 271 ms
targetHost> warning: unable to download 'https://cache.nixos.org/12j3ls4rivh5szg90imgd7qzfjg5gvd2.narinfo': Couldn't resolve host name (6); retrying in 349 ms
targetHost> warning: unable to download 'https://cache.nixos.org/2ahyp05yl3v55k18zin67sjjhxikl769.narinfo': Couldn't resolve host name (6); retrying in 289 ms
targetHost> warning: unable to download 'https://cache.nixos.org/2z7cz6gc58168caifq9p3w4cl5bhn1bd.narinfo': Couldn't resolve host name (6); retrying in 299 ms
targetHost> warning: unable to download 'https://cache.nixos.org/2z7cz6gc58168caifq9p3w4cl5bhn1bd.narinfo': Couldn't resolve host name (6); retrying in 2825 ms
[...]
targetHost> error (ignored): unable to download 'https://cache.nixos.org/12j3ls4rivh5szg90imgd7qzfjg5gvd2.narinfo': Couldn't resolve host name (6)
targetHost> error (ignored): unable to download 'https://cache.nixos.org/2ahyp05yl3v55k18zin67sjjhxikl769.narinfo': Couldn't resolve host name (6)
targetHost> error (ignored): unable to download 'https://cache.nixos.org/2z7cz6gc58168caifq9p3w4cl5bhn1bd.narinfo': Couldn't resolve host name (6)
targetHost> error: unable to download 'https://cache.nixos.org/0xhjv5m80j0a3dik7kgf9s3qbsxizncj.narinfo': Couldn't resolve host name (6)
targetHost> error: unexpected end-of-file
Traceback (most recent call last):
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1010, in _deploy
    max_concurrent_copy=max_concurrent_copy)
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 694, in copy_closures
    tasks=self.active.itervalues(), worker_fun=worker)
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 690, in worker
    m.copy_closure_to(m.new_toplevel)
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 367, in copy_closure_to
    env=env)
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 324, in _logged_exec
    return nixops.util.logged_exec(command, self.logger, **kwargs)
  File "/nix/store/qhvd7z3i0kr8hvc5r56wxcy9ra2sqwqh-nixops-1.7/lib/python2.7/site-packages/nixops/util.py", line 152, in logged_exec
    raise CommandFailed(err, res)
nixops.util.CommandFailed: command ‘['nix-copy-closure', '--to', 'root@192.168.99.7', u'/nix/store/8gac9nx5c4w0gcfxg1ahfh86ksi7h12x-nixos-system-bios-20.03pre-git', '--use-substitutes']’ failed on machine ‘targetHost’ (exit code 1)

```

**Comment by blitz** [comment]
After grepping through the source code I found:

```
 deployment.hasFastConnection = true;
```

This does the trick. Nevermind. :)

**Comment by jhillyerd** [comment]
That is a really ambiguous name for a configuration option, perhaps we re-open & convert this bug into a request to rename it to something that conveys what it does?

> deployment.hasFastConnection
> If set to true, whole closure will be copied using just `nix-copy-closure`.
> 
> If set to false, closure will be copied first using binary substitution. Addtionally, any missing derivations copied with `nix-copy-closure` will be done using --gzip flag.
> 
> Some backends set this value to true.
> 
> Type: boolean
> 
> Default: false

It sounds like it's affecting multiple deployment settings, which could also be frustrating if a user only wishes to alter one of them.
