### ISSUE TITLE
KeyError: 'path' when using autoLuks keys

### ISSUE THREAD

**Issue by tewfik-ghariani** [NixOS/nixops#1408]
Hello, not sure if this is supposed to be a "nixops", "nixos-modules-contrib" or "nixops-gcp" issue but here is my situation :

I'm bringing up a GCP cluster while using the auto-luks module defined here : https://github.com/nix-community/nixos-modules-contrib/blob/master/auto-luks/default.nix

I'm enabling the _encrypt_ option which is defined here in nixops-gcp : 
https://github.com/nix-community/nixops-gce/blob/master/nixops_gcp/nix/gce.nix#L443-L450

But the deployment failed with the following

```
machine..........> error: Traceback (most recent call last):
  File "/data/home/deploy-ops/.cache/pypoetry/virtualenvs/nixops-gcp-jVDHgLjj-py3.7/src/nixops/nixops/deployment.py", line 992, in worker
    m.send_keys()
  File "/data/home/deploy-ops/.cache/pypoetry/virtualenvs/nixops-gcp-jVDHgLjj-py3.7/src/nixops/nixops/backends/__init__.py", line 357, in send_keys
    self.log("uploading key ‘{0}’ to ‘{1}’...".format(k, opts["path"]))
KeyError: 'path'
```
After some debugging, I've seen that the '**path**' attribute is missing from the key generated by Luks ( and the keyFile is wrong )

```
luks-ops-testing-machine-ee867d-volume
{'text': '*************Q==', 'keyFile': '/run/keysluks-ops-testing-machine-ee867d-volume', 'destDir': '/run/keys', 'group': 'root', 'permissions': '0600', 'user': 'root'}
```

I believe this has something to do with https://github.com/NixOS/nixops/pull/1378 but I'm a bit lost in regards to where this should be fixed

Any help would be appreciated
cc @adisbladis, @ryantm

**Comment by tewfik-ghariani** [comment]
This shall be fixed after merging the 3 referenced PRs

cc @AmineChikhaoui
