### ISSUE TITLE
Could not find file for the medium - vmdk not found in /nix/store

### ISSUE THREAD

**Issue by AdrianRibao** [NixOS/nixops#1431]
I'm trying to run a deploy but I get this error:

```
webserver> creating VirtualBox VM...
webserver> Virtual machine 'nixops-60951791-596a-11eb-b0e2-cd08241dfc14-webserver' is created and registered.
webserver> UUID: a5aacb37-29f5-453e-9a96-403632d99c43
webserver> Settings file: '/home/myuser/VMs/nixops-60951791-596a-11eb-b0e2-cd08241dfc14-webserver/nixops-60951791-596a-11eb-b0e2-cd08241dfc14-webserver.vbox'
webserver> creating disk ‘disk1’...
webserver> VBoxManage: error: Could not find file for the medium '/nix/store/bidfjskkx678vk69h3wdcvq3p7af2azm-virtualbox-nixops-21.03.vmdk' (VERR_FILE_NOT_FOUND)
webserver> VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium, callee nsISupports
webserver> VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 187 of file VBoxManageDisk.cpp
```

Thanks!

**Comment by JulesdeCube** [comment]
same error with nixops 2.0

```
compute_1> creating disk ‘disk1’...
compute_1> VBoxManage: error: Could not find file for the medium '/nix/store/krc3mx6xr9z9dqi56m7kgwbcb6p9795m-virtualbox-nixops-21.11.vmdk' (VERR_FILE_NOT_FOUND)
compute_1> VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium, callee nsISupports
compute_1> VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 187 of file VBoxManageDisk.cpp
Traceback (most recent call last):
  File "/nix/store/bca37id2mkw7nv03kd6zrajs69iyhwc6-python3.8-nixops-2.0.0/bin/.nixops-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/__main__.py", line 56, in main
    args.op(args)
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/script_defs.py", line 715, in op_deploy
    depl.deploy(
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/deployment.py", line 1352, in deploy
    self.run_with_notify("deploy", lambda: self._deploy(**kwargs))
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/deployment.py", line 1341, in run_with_notify
    f()
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/deployment.py", line 1352, in <lambda>
    self.run_with_notify("deploy", lambda: self._deploy(**kwargs))
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/deployment.py", line 1255, in _deploy
    nixops.parallel.run_tasks(
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/parallel.py", line 106, in run_tasks
    raise list(exceptions.values())[0]
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/parallel.py", line 70, in thread_fun
    work_result = (worker_fun(t), None, t.name)
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/deployment.py", line 1207, in worker
    r.create(
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixopsvbox/backends/virtualbox.py", line 409, in create
    self._logged_exec(
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/backends/__init__.py", line 582, in _logged_exec
    return nixops.util.logged_exec(command, self.logger, **kwargs)
  File "/nix/store/7w0556wlj4sl1r8wy0alq6dilyg0dp7n-python3-3.8.9-env/lib/python3.8/site-packages/nixops/util.py", line 372, in logged_exec
    raise CommandFailed(err, res)
nixops.util.CommandFailed: command ‘['VBoxManage', 'clonehd', '/nix/store/krc3mx6xr9z9dqi56m7kgwbcb6p9795m-virtualbox-nixops-21.11.vmdk', '/home/jules/Vbox/nixops-2cd0a6d9-deea-11ec-85c5-4c796edac55a-compute_1/disk1.vdi', '--format', 'VDI']’ failed on machine ‘compute_1’ (exit code 1)
```
