### ISSUE TITLE
ModuleNotFoundError: No module named 'nixops.plugin'

### ISSUE THREAD

**Issue by cprussin** [NixOS/nixops#1462]
At some point, since pulling latest master, I'm seeing the following stack trace whenever I try to run `nixops deploy`:

```
Traceback (most recent call last):
  File "/nix/store/ziiia5s0lw0xc65fnj1npzi4sjl0r9kw-python3.8-nixops-2.0.0/bin/.nixops-wrapped", line 6, in <module>
    from nixops.__main__ import main
  File "/nix/store/147c873ip15lgd2c4mjp9939lmbzp05r-nixops/lib/python3.8/site-packages/nixops/__main__.py", line 34, in <module>
    from nixops.script_defs import (
  File "/nix/store/147c873ip15lgd2c4mjp9939lmbzp05r-nixops/lib/python3.8/site-packages/nixops/script_defs.py", line 31, in <module>
    PluginManager.load()
  File "/nix/store/147c873ip15lgd2c4mjp9939lmbzp05r-nixops/lib/python3.8/site-packages/nixops/plugins/manager.py", line 57, in load
    for plugin in get_plugins():
  File "/nix/store/147c873ip15lgd2c4mjp9939lmbzp05r-nixops/lib/python3.8/site-packages/nixops/plugins/__init__.py", line 27, in get_plugins
    pm = get_plugin_manager()
  File "/nix/store/147c873ip15lgd2c4mjp9939lmbzp05r-nixops/lib/python3.8/site-packages/nixops/plugins/__init__.py", line 22, in get_plugin_manager
    pm.load_setuptools_entrypoints("nixops")
  File "/nix/store/8l4f3gqm1qdqmn5846dlkqn475r4yjq7-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'nixops.plugin'
```

I have not bisected the git history to find exactly which commit introduced the issue yet.

**Comment by cprussin** [comment]
Seems to have been fixed at some point
