### ISSUE TITLE
Multiple exceptions: need more than 1 value to unpack, need more than 1 value to unpack

### ISSUE THREAD

**Issue by peti** [NixOS/nixops#156]
nixops can no longer deploy machines in EC2. I tried the 1.1.1 release and the latest version from git, but both versions just give this error:

    $ nixops deploy
    slave2> waiting for IP address... 
    slave1> waiting for IP address... 
    slave2> [running] 79.125.81.202 / 10.73.183.230
    slave1> [running] 54.217.176.190 / 10.73.133.146
    error: Multiple exceptions: need more than 1 value to unpack, need more than 1 value to unpack

The --debug option adds this output:

    error: Multiple exceptions: need more than 1 value to unpack, need more than 1 value to unpack
    ------------------------------
    Traceback (most recent call last):
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/parallel.py", line 41, in thread_fun
        result_queue.put((worker_fun(t), None))
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/deployment.py", line 869, in worker
        r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/backends/ec2.py", line 825, in create
        self._wait_for_ip(instance)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/backends/ec2.py", line 295, in _wait_for_ip
        nixops.known_hosts.add(instance.ip_address, self.public_host_key)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/known_hosts.py", line 44, in add
        _rewrite(ip_address, public_host_key)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/known_hosts.py", line 27, in _rewrite
        new = [ l for l in [ rewrite(l) for l in contents.splitlines() ] if l is not None ]
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/known_hosts.py", line 23, in rewrite
        (names, rest) = l.split(' ', 1)
    ValueError: need more than 1 value to unpack
    ------------------------------
    Traceback (most recent call last):
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/parallel.py", line 41, in thread_fun
        result_queue.put((worker_fun(t), None))
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/deployment.py", line 869, in worker
        r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/backends/ec2.py", line 825, in create
        self._wait_for_ip(instance)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/backends/ec2.py", line 295, in _wait_for_ip
        nixops.known_hosts.add(instance.ip_address, self.public_host_key)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/known_hosts.py", line 44, in add
        _rewrite(ip_address, public_host_key)
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/known_hosts.py", line 27, in _rewrite
        new = [ l for l in [ rewrite(l) for l in contents.splitlines() ] if l is not None ]
      File "/nix/store/1c7r69fya6xyrly2zdpd5mpw7vk955rw-nixops-1.1.1/lib/python2.7/site-packages/nixops-1.1.1-py2.7.egg/nixops/known_hosts.py", line 23, in rewrite
        (names, rest) = l.split(' ', 1)
    ValueError: need more than 1 value to unpack

**Comment by blast-hardcheese** [comment]
So, 2d309eb only does comment sanitization, but there are actually quite a few other configurations that are probably not correctly handled by `known_hosts.py`. I was only using comments, which is what triggered this issue for me, but I suspect someone with a more aggressive known_hosts file will run into more problems.

**Comment by blast-hardcheese** [comment]
Actually, I'm blind. I just nuked all the formatting and comments I had in my `known_hosts` file.

**Comment by blast-hardcheese** [comment]
Ah, one more thing, I didn't notice that we were just using `StrictHostKeyChecking=no`, instead of scanning and writing it ourselves. A cursory scan didn't reveal where the call was actually happening, I'll look more tomorrow.

**Comment by blast-hardcheese** [comment]
These patches are only tested somewhat thoroughly on Virtualbox, as it was preventing me from even getting started with nixops. I don't know the codebase, I don't even know nix that well, I just would like to use nix and nixops for a project. I'd love to discuss and help with this issue further, if anyone has any more ideas.
