### ISSUE TITLE
New SSL Certificate for Hetzner

### ISSUE THREAD

**Issue by fuzzy-id** [NixOS/nixops#354]
Looks like Hetzner exchanged their certificate. Here is the stacktrace:

```
rootsrv> creating an exclusive robot admin account for ‘rootsrv’... Traceback (most recent call last):
  File "/nix/store/fcyq80ma0bni15acjnw5zw8ahh6ib3wn-nixops-1.3/bin/..nixops-wrapped-wrapped", line 923, in <module>
    args.op()
  File "/nix/store/fcyq80ma0bni15acjnw5zw8ahh6ib3wn-nixops-1.3/bin/..nixops-wrapped-wrapped", line 373, in op_deploy
    repair=args.repair)
  File "/nix/store/fcyq80ma0bni15acjnw5zw8ahh6ib3wn-nixops-1.3/lib/python2.7/site-packages/nixops/deployment.py", line 938, in deploy
    self._deploy(**kwargs)
  File "/nix/store/fcyq80ma0bni15acjnw5zw8ahh6ib3wn-nixops-1.3/lib/python2.7/site-packages/nixops/deployment.py", line 897, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/fcyq80ma0bni15acjnw5zw8ahh6ib3wn-nixops-1.3/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/fcyq80ma0bni15acjnw5zw8ahh6ib3wn-nixops-1.3/lib/python2.7/site-packages/nixops/deployment.py", line 873, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/fcyq80ma0bni15acjnw5zw8ahh6ib3wn-nixops-1.3/lib/python2.7/site-packages/nixops/backends/hetzner.py", line 560, in create
    self.robot_admin_pass) = server.admin.create()
  File "/nix/store/0binlviwp0lbkfkbxcrm7j6b2vvzk07f-python2.7-hetzner-0.7.3/lib/python2.7/site-packages/hetzner/server.py", line 358, in admin
    self._admin_account = AdminAccount(self)
  File "/nix/store/0binlviwp0lbkfkbxcrm7j6b2vvzk07f-python2.7-hetzner-0.7.3/lib/python2.7/site-packages/hetzner/server.py", line 170, in __init__
    self.update_info()
  File "/nix/store/0binlviwp0lbkfkbxcrm7j6b2vvzk07f-python2.7-hetzner-0.7.3/lib/python2.7/site-packages/hetzner/server.py", line 176, in update_info
    self._scraper.login()
  File "/nix/store/0binlviwp0lbkfkbxcrm7j6b2vvzk07f-python2.7-hetzner-0.7.3/lib/python2.7/site-packages/hetzner/robot.py", line 118, in login
    response = self.request('/login', xhr=False)
  File "/nix/store/0binlviwp0lbkfkbxcrm7j6b2vvzk07f-python2.7-hetzner-0.7.3/lib/python2.7/site-packages/hetzner/robot.py", line 158, in request
    self.conn.request(method, path, encoded, headers)
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/nix/store/0binlviwp0lbkfkbxcrm7j6b2vvzk07f-python2.7-hetzner-0.7.3/lib/python2.7/site-packages/hetzner/robot.py", line 50, in connect
    ca_certs=ca_certs.name)
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/nix/store/49zg30nx308mad45yd9vd4pk3jlddkks-python-2.7.10/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by rbvermaa** [comment]
@fuzzy-id is this on nixos or on another distribution? If the latter, perhaps it might be solved by setting SSL_CERT_FILE environment variable to point to the location of your certificate bundle (in NixOS it is at /etc/ssl/certs/ca-certificates.crt)

**Comment by fuzzy-id** [comment]
It's on NixOS. The certificate is [hard coded into the Hetzner part]
(https://github.com/RedMoonStudios/hetzner/blob/master/hetzner/util/http.py). I haven't tried   `SSL_CERT_FILE` but looking at the code I don't see how it could make a difference. Such a feature would be nice to have though.

**Comment by rbvermaa** [comment]
@fuzzy-id OK thnx, just wanted to make sure. I redeployed a new cluster last week, and didn't get the issue. 

@aszlig could you update the hetzner library? Perhaps we should allow the cert to be overridden, so we do not necessarily need to update the library, if we don't want to?

**Comment by rbvermaa** [comment]
@aszlig Why can't we use the certificates from $SSL_CERT_FILE actually?

**Comment by aszlig** [comment]
@rbvermaa: I'll update the library and include a way to override certificates.
