### ISSUE TITLE
If sshd is socket activated, nixops tries to restart sshd instances and kills own connection

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixops#460]
If you set ```services.ssh.startWhenNeeded = true```, nixops will try to restart the sshd instances - including its own which causes nixops to error out:

```
nas> restarting the following units: polkit.service, sshd@0-long_ipv6_address:50274.service
Bad packet length 2902299502.
ssh_dispatch_run_fatal: Connection to ipv6_address port 22: Connection corrupted
nas> error: unable to activate new configuration
```

It should basically leave any ```sshd@``` units alone.

**Comment by kevincox** [comment]
I have the same issue.

**Comment by peterhoeg** [comment]
@kevincox, are you still seeing this?

**Comment by kevincox** [comment]
Yup. I just updated today:

```
physical> closures copied successfully
t6> stopping the following units: cpufreq.service, kmod-static-nodes.service, network-local-commands.service, network-setup.service, nix-daemon.service, nix-daemon.socket, nix-gc.timer, nixops-keys.service, systemd-binfmt.service, systemd-modules-load.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service, zram-reloader.service
t3> NOT restarting the following changed units: getty@tty1.service, systemd-backlight@backlight:acpi_video0.service, systemd-fsck@dev-sda1.service, systemd-journal-flush.service, systemd-logind.service, systemd-random-seed.service, systemd-remount-fs.service, systemd-tmpfiles-setup.service, systemd-udev-settle.service, systemd-update-utmp.service, systemd-user-sessions.service, user-runtime-dir@0.service, user@0.service, zram-init-zram0.service
t3> activating the configuration...
t3> setting up /etc...
t3> restarting systemd...
t3> reloading user units for root...
t3> setting up tmpfiles
t3> reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, sys-kernel-debug.mount
t3> restarting the following units: dhcpcd.service, nginx.service, sshd@12-2a02:8084:d6bb:e800:2e0:4cff:fe68:4775:22-2a02:8084:d6bb:e800:933e:55c:1a41:de33:43176.service, systemd-journald.service
Bad packet length 3116670498.
ssh_dispatch_run_fatal: Connection to 2a02:8084:d6bb:e800:2e0:4cff:fe68:4775 port 22: Connection corrupted
t3> error: Traceback (most recent call last):
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 743, in worker
    raise Exception("unable to activate new configuration (exit code {})".format(res))
Exception: unable to activate new configuration (exit code 255)

Traceback (most recent call last):
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1019, in _deploy
    dry_activate=dry_activate, max_concurrent_activate=max_concurrent_activate)
  File "/nix/store/ag4zl99kg2d0syij37dp5xhisi0vqfy0-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 775, in activate_configs
    .format(len(failed), len(res), ", ".join(["‘{0}’".format(x) for x in failed])))
Exception: activation of 1 of 1 machines failed (namely on ‘t3’)
```

**Comment by peterhoeg** [comment]
Deploying from 19.03 to 19.03?

Oddly enough I don't have this problem any more (we use nixops extensively), but maybe we worked around it locally...

**Comment by kevincox** [comment]
I'm running nixpkgs-unstable.

**Comment by peterhoeg** [comment]
Right, so how on earth did we fix it/work around it on this side and why hasn't that been upstreamed.... The plot thickens.

**Comment by kevincox** [comment]
On 7/22/19 8:56 AM, Peter Hoeg wrote:
>
> Right, so how on earth did we fix it/work around it on this side and 
> why hasn't that been upstreamed.... The plot thickens.
>
Are you sure that your SSH changed in the upgrade you tested? Especially 
if you are pinned to a version I suspect that sshd and its config 
doesn't change often.

**Comment by peterhoeg** [comment]
Well, this hasn't been an issue for a very long time across multiple versions 18.xx up until now. Deploying from unstable with all servers running 19.03 and no pinning of any versions of anything in nixpkgs.
