### ISSUE TITLE
nixops deploy on OSX fails with TypeError: expected a string or other character buffer object

### ISSUE THREAD

**Issue by ElessarWebb** [NixOS/nixops#507]
Running `deploy --dry-run -d <name>` on OSX fails with the following trace.
Keys aren't set up yet for access to the deployment host. But the error is strange.

```
Traceback (most recent call last):
  File "/nix/store/71i5wmxfv8f2sizbl24wdxfafsz5qhlp-nixops-1.4/bin/..nixops-wrapped-wrapped", line 939, in <module>
    args.op()
  File "/nix/store/71i5wmxfv8f2sizbl24wdxfafsz5qhlp-nixops-1.4/bin/..nixops-wrapped-wrapped", line 374, in op_deploy
    repair=args.repair, dry_activate=args.dry_activate)
  File "/nix/store/71i5wmxfv8f2sizbl24wdxfafsz5qhlp-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 971, in deploy
    self._deploy(**kwargs)
  File "/nix/store/71i5wmxfv8f2sizbl24wdxfafsz5qhlp-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 934, in _deploy
    self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/71i5wmxfv8f2sizbl24wdxfafsz5qhlp-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 602, in build_configs
    key_file = m.get_ssh_private_key_file()
  File "/nix/store/71i5wmxfv8f2sizbl24wdxfafsz5qhlp-nixops-1.4/lib/python2.7/site-packages/nixops/backends/none.py", line 74, in get_ssh_private_key_file
    return self.write_ssh_private_key(self._ssh_private_key)
  File "/nix/store/71i5wmxfv8f2sizbl24wdxfafsz5qhlp-nixops-1.4/lib/python2.7/site-packages/nixops/backends/__init__.py", line 272, in write_ssh_private_key
    f.write(private_key)
TypeError: expected a string or other character buffer object
```

**Comment by rbvermaa** [comment]
Do you get the same error without --dry-run?

**Comment by ElessarWebb** [comment]
I actually got further by removing `--dry-run` and adding `--check`. 
The latter set up ssh, so that might have fixed the weird private-key related issue. I will check that and report back, but the error is very non-descriptive.

**Comment by ElessarWebb** [comment]
Couldn't replicate it anymore

**Comment by wmertens** [comment]
Getting the same error, also on macOS, running `nixops deploy --build-only` on a fresh deployment to a NixOS host (so just `deployment.targetHost` specified). I had to add `--debug` to get this trace:

```
[...stuff]
Traceback (most recent call last):
  File "/nix/store/r9w6pn14i50l55vijp9hgngcnlw9swg2-nixops-1.5.2/bin/..nixops-wrapped-wrapped", line 955, in <module>
    args.op()
  File "/nix/store/r9w6pn14i50l55vijp9hgngcnlw9swg2-nixops-1.5.2/bin/..nixops-wrapped-wrapped", line 382, in op_deploy
    repair=args.repair, dry_activate=args.dry_activate)
  File "/nix/store/r9w6pn14i50l55vijp9hgngcnlw9swg2-nixops-1.5.2/lib/python2.7/site-packages/nixops/deployment.py", line 983, in deploy
    self._deploy(**kwargs)
  File "/nix/store/r9w6pn14i50l55vijp9hgngcnlw9swg2-nixops-1.5.2/lib/python2.7/site-packages/nixops/deployment.py", line 951, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/r9w6pn14i50l55vijp9hgngcnlw9swg2-nixops-1.5.2/lib/python2.7/site-packages/nixops/deployment.py", line 602, in build_configs
    key_file = m.get_ssh_private_key_file()
  File "/nix/store/r9w6pn14i50l55vijp9hgngcnlw9swg2-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/none.py", line 78, in get_ssh_private_key_file
    return self.write_ssh_private_key(self._ssh_private_key)
  File "/nix/store/r9w6pn14i50l55vijp9hgngcnlw9swg2-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/__init__.py", line 307, in write_ssh_private_key
    f.write(private_key)
TypeError: expected a string or other character buffer object
```

Something something ssh key management @rbvermaa ?

**Comment by wmertens** [comment]
I was able to get it to create a keypair by running `deploy` without arguments until it printed `generating keypair` and then aborting. It seems that `--build-only` skips some init step…
