### ISSUE TITLE
Error deploying to GCE: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixops#518]
I'm trying to deploy a simple load balancing example to GCE but I get the following error. Deploying to VirtualBox works. Also, I noticed it's using libcloud 0.18.0 when 1.2 is [already out](https://github.com/apache/libcloud/releases). Why is nixops using such an old version?

``` shell
$ nixops deploy -d load-balancer-gce --debug
[snip]

proxy....> creating GCE disk of auto GiB from image 'n-c33b57738b4411e6928dacbc32aa73f1-bootstrap'...
backend1.> creating GCE disk of auto GiB from image 'n-c33b57738b4411e6928dacbc32aa73f1-bootstrap'...
No handlers could be found for logger "libcloud.common.google"
backends.> updating the machine list of GCE target pool 'n-c33b57738b4411e6928dacbc32aa73f1-backends'...
error: Multiple exceptions: {u'domain': u'global', u'message': u"Code: '53E3742CDEB21.A6A4541.E40BA01D'", u'reason': u'backendError'}, 'NoneType' object has no attribute 'name', 'NoneType' object has no attribute 'name'
------------------------------
Traceback (most recent call last):
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 901, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/resources/gce_target_pool.py", line 162, in create
    tp.add_node(uri)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 721, in add_node
    return self.driver.ex_targetpool_add_node(targetpool=self, node=node)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 3037, in ex_targetpool_add_node
    data=targetpool_data)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/common/base.py", line 929, in async_request
    response = request(**kwargs)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 120, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/common/google.py", line 692, in request
    *args, **kwargs)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/common/base.py", line 799, in request
    response = responseCls(**kwargs)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/common/base.py", line 145, in __init__
    self.object = self.parse_body()
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/common/google.py", line 279, in parse_body
    raise GoogleBaseError(message, self.status, code)
GoogleBaseError: {u'domain': u'global', u'message': u"Code: '53E3742CDEB21.A6A4541.E40BA01D'", u'reason': u'backendError'}
------------------------------
Traceback (most recent call last):
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 901, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/backends/gce.py", line 350, in create
    use_existing= False)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 2816, in create_volume
    size, name, location, snapshot, image, ex_disk_type)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 4973, in _create_vol_req
    API_VERSION, self.project, location.name, ex_disk_type)
AttributeError: 'NoneType' object has no attribute 'name'
------------------------------
Traceback (most recent call last):
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 901, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/z4mccd3kyhq88mb35a2gw5h03xx646bd-nixops-1.4/lib/python2.7/site-packages/nixops/backends/gce.py", line 350, in create
    use_existing= False)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 2816, in create_volume
    size, name, location, snapshot, image, ex_disk_type)
  File "/nix/store/a6v59ncn7wh2a13lj9wipnf7xxdl4c3i-python2.7-libcloud-0.18.0/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 4973, in _create_vol_req
    API_VERSION, self.project, location.name, ex_disk_type)
AttributeError: 'NoneType' object has no attribute 'name'
```

My nix files look like this:
### `load-balancer.nix`

``` nix
let

  backend =
    { config, pkgs, ... }:
    { services.nginx.enable = true;
      services.nginx.statusPage = true;
      networking.firewall.allowedTCPPorts = [ 80 ];
    };

in

{
  network.description = "Load balancing network";

  proxy =
    { config, pkgs, nodes, ... }:
    { services.nginx.enable = true;
      services.nginx.httpConfig = ''
        upstream mysite_app {
            ip_hash;
            server backend1;
        }

        server {
          listen 80;
          server_name mysite.com;
          root /var/www/mysite.com/;

          location / {
            proxy_pass backend1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }
        }
      '';
      networking.firewall.allowedTCPPorts = [ 80 ];
    };

  backend1 = backend;
}
```
### `load-balancer-gce.nix`

``` nix
let

  # change this as necessary or wipe and use ENV vars
  credentials = {
    project = "...";  # hidden
    serviceAccount = "...";  # hidden
    accessKey = "key.pem";
  };

  gce = { resources, ...}:  {
    networking.firewall.allowedTCPPorts = [ 80 ];
    deployment.targetEnv = "gce";
    deployment.gce = credentials // {
      region = "us-central1";
      tags = [ "public-http" ];
      network = resources.gceNetworks.lb-net;
    };
  };

in {

  # create a network that allows SSH traffic(by default), pings
  # and HTTP traffic for machines tagged "public-http"
  resources.gceNetworks.lb-net = credentials // {
    addressRange = "192.168.4.0/24";
    firewall = {
      allow-http = {
        targetTags = [ "public-http" ];
        allowed.tcp = [ 80 ];
      };
      allow-ping.allowed.icmp = null;
    };
  };

  # by default, health check pings port 80, so we don't have to set anything
  resources.gceHTTPHealthChecks.plain-hc = credentials;

  resources.gceTargetPools.backends = { resources, nodes, ...}: credentials // {
    region = "us-central1";
    healthCheck = resources.gceHTTPHealthChecks.plain-hc;
    machines = [ nodes.backend1 ];
  };

  proxy    = gce;
  backend1 = gce;

}
```

**Comment by 3noch** [comment]
I've paired down the config to the following and still get the same error:

### `load-balancer.nix`
```nix
{
  proxy =
    { config, pkgs, nodes, ... }:
    { services.nginx.enable = true; };
}
```

### `load-balancer-gce.nix`
```nix
let
  credentials = {
    project = "...";  # hidden
    serviceAccount = "..."; # hidden
    accessKey = "key.pem";
  };

  gce = { resources, ...}:  {
    deployment.targetEnv = "gce";
    deployment.gce = credentials // {
      region = "us-central1";
    };
  };

in {
  proxy    = gce;
}
```

**Comment by domenkozar** [comment]
cc @rbvermaa

**Comment by 3noch** [comment]
I think I *may* have found where this "bug" is coming from. For machines (instances) the `region` must include a letter like `us-central1-b` instead of just `us-central1`.

**Comment by 3noch** [comment]
It would be wonderful if the error message was more informative. ;)
