### ISSUE TITLE
Sqlite error during EC2 deployment

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixops#547]
I'm deploying 100 nodes to EC2 and I get two exceptions back as following:

```
Traceback (most recent call last):
  File "/nix/store/h9lvvmc17ab6ajv0phpqankwlwj9z79s-nixops-1.4/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/h9lvvmc17ab6ajv0phpqankwlwj9z79s-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 901, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/h9lvvmc17ab6ajv0phpqankwlwj9z79s-nixops-1.4/lib/python2.7/site-packages/nixops/backends/ec2.py", line 931, in create
    if self.instance_type != defn.instance_type:
  File "/nix/store/h9lvvmc17ab6ajv0phpqankwlwj9z79s-nixops-1.4/lib/python2.7/site-packages/nixops/util.py", line 214, in get
    s = self._get_attr(name, default)
  File "/nix/store/h9lvvmc17ab6ajv0phpqankwlwj9z79s-nixops-1.4/lib/python2.7/site-packages/nixops/resources/__init__.py", line 89, in _get_attr
    c.execute("select value from ResourceAttrs where machine = ? and name = ?", (self.id, name))
InterfaceError: Error binding parameter 0 - probably unsupported type.
```

Need to investigate what's happening.

**Comment by domenkozar** [comment]
```
(Pdb) !c.execute("select value from ResourceAttrs where machine = ? and name = ?", (self.id, name)).fetchone()
(u'ssh-ed25519 XXX root@ip-XXX.eu-central-1.compute.internal',)
```

Huh, this is highly suspicious to be a threading issue.

**Comment by domenkozar** [comment]
@rbvermaa did you ever notice this?

**Comment by domenkozar** [comment]
I'm using the following workaround until we come to the bottom of this:

```
diff --git a/nixops/resources/__init__.py b/nixops/resources/__init__.py
index 4e1aa7b..da2ee20 100644
--- a/nixops/resources/__init__.py
+++ b/nixops/resources/__init__.py
@@ -86,7 +86,13 @@ class ResourceState(object):
         """Get a machine attribute from the state file."""
         with self.depl._db:
             c = self.depl._db.cursor()
-            c.execute("select value from ResourceAttrs where machine = ? and name =
 ?", (self.id, name))
+            if not isinstance(self.id, int):
+                import pdb;pdb.set_trace()
+            try:
+                c.execute("select value from ResourceAttrs where machine = ? and name = ?", (self.id, name))
+            except:
+                print self.id
+                c.execute("select value from ResourceAttrs where machine = ? and name = ?", (self.id, name))
             row = c.fetchone()
             if row != None: return row[0]
             return nixops.util.undefined
```

**Comment by domenkozar** [comment]
According to http://stackoverflow.com/a/22739924 it's not safe to share sqlite connection between threads.

**Comment by rbvermaa** [comment]
@domenkozar Yeah, never been able to reproduce it though, it happens to us very rarely.

**Comment by domenkozar** [comment]
I see that we use `RLock` within `with db` statements so that should be correct.

I'm testing now if https://bugs.python.org/issue10513 fixes this issue.
