### ISSUE TITLE
Intermittent error while provisioning security groups

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixops#677]
```
created deployment ‘a04f9035-4adc-11e7-9a8a-06258a1e40fd’
a04f9035-4adc-11e7-9a8a-06258a1e40fd
Deploying cluster...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0  21523      0 --:--:-- --:--:-- --:--:-- 13000
cardanod-ip................> creating elastic IP address (region ‘eu-central-1’)...
allow-all-ap-northeast-2...> creating EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-northeast-2’...
allow-all-ap-southeast-1...> creating EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-southeast-1’...
hydra-ip...................> creating elastic IP address (region ‘eu-central-1’)...
allow-all-eu-west-2........> creating EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-eu-west-2’...
allow-all-eu-central-1.....> creating EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-eu-central-1’...
allow-all-ap-southeast-2...> creating EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-southeast-2’...
allow-all-eu-west-1........> creating EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-eu-west-1’...
allow-all-ap-northeast-1...> creating EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-northeast-1’...
allow-all-eu-central-1.....> adding new rules to EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-eu-central-1’...
cardano-test-eu-central....> uploading EC2 key pair ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-cardano-test-eu-central’...
cardanod-ip................> IP address is 52.28.53.64
cardano-test-eu-west-2.....> uploading EC2 key pair ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-cardano-test-eu-west-2’...
hydra-ip...................> IP address is 52.58.250.64
allow-all-eu-west-2........> adding new rules to EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-eu-west-2’...
cardano-test-eu-west-1.....> uploading EC2 key pair ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-cardano-test-eu-west-1’...
allow-all-eu-west-1........> adding new rules to EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-eu-west-1’...
cardano-test-ap-southeast-1> uploading EC2 key pair ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-cardano-test-ap-southeast-1’...
allow-all-ap-southeast-1...> adding new rules to EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-southeast-1’...
allow-all-ap-northeast-1...> adding new rules to EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-northeast-1’...
cardano-test-ap-northeast-2> uploading EC2 key pair ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-cardano-test-ap-northeast-2’...
allow-all-ap-northeast-2...> adding new rules to EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-northeast-2’...
cardano-test-ap-northeast-1> uploading EC2 key pair ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-cardano-test-ap-northeast-1’...
cardano-test-ap-southeast-2> uploading EC2 key pair ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-cardano-test-ap-southeast-2’...
allow-all-ap-southeast-2...> adding new rules to EC2 security group ‘charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-ap-southeast-2’...
error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'charon-a04f9035-4adc-11e7-9a8a-06258a1e40fd-allow-all-eu-central-1' does not exist in default VPC 'vpc-
55279c3c'</Message></Error></Errors><RequestID>5cc0f840-0904-44d0-9862-43c7a82b58f6</RequestID></Response>
Infra.hs: ShellFailed {shellCommandLine = "GC_INITIAL_HEAP_SIZE=$((8*1024*1024*1024)) SMART_GEN_IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4) nixops deploy --show-trace -d io
hk-infra -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/05126bc8503a37bfd2fe80867eb5b0bea287c633.tar.gz --max-concurrent-copy 50 -j 4", shellExitCode = ExitFailure 1}
```
Possible cause could be a race condition between finalization of group creation and reference of the group id in further invocations.

**Comment by domenkozar** [comment]
@deepfire if it happens again to you, can you run it with `--debug` to get python traceback? It's going to simplify the debugging.

**Comment by cleverca22** [comment]
```
------------------------------
Traceback (most recent call last):
  File "/nix/store/f9d968lljwp9ij5q1dydxg14r7377m8q-nixops-1.5.2pre0_abcdef/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/f9d968lljwp9ij5q1dydxg14r7377m8q-nixops-1.5.2pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 917, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/f9d968lljwp9ij5q1dydxg14r7377m8q-nixops-1.5.2pre0_abcdef/lib/python2.7/site-packages/nixops/resources/ec2_security_group.py", line 181, in create
    grp.authorize(ip_protocol=rule[0], from_port=rule[1], to_port=rule[2], cidr_ip=rule[3])
  File "/nix/store/xqfzzywv0rf2g56ffzz92fsh4aq4p9n4-python2.7-boto-2.45.0/lib/python2.7/site-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/nix/store/xqfzzywv0rf2g56ffzz92fsh4aq4p9n4-python2.7-boto-2.45.0/lib/python2.7/site-packages/boto/ec2/connection.py", line 3207, in authorize_security_group
    params, verb='POST')
  File "/nix/store/xqfzzywv0rf2g56ffzz92fsh4aq4p9n4-python2.7-boto-2.45.0/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'charon-9dd86c05-cc63-11e7-868d-06258a1e40fd-allow-cardano-public-tcp-eu-central-1' does not exist in default VPC 'vpc-XXX'</Message></Error></Errors><RequestID>3ee017ab-582b-4937-9b30-0bc1ea1f15c5</RequestID></Response>
```

**Comment by rbvermaa** [comment]
Pushed e601c17, which should fix this issue.
