### ISSUE TITLE
Disassociate EIP from an instance in VPC fails 

### ISSUE THREAD

**Issue by AmineChikhaoui** [NixOS/nixops#678]
```
frontend> disassociating IP address ‘54.235.75.201’...
Traceback (most recent call last):
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/bin/..nixops-wrapped-wrapped", line 951, in <module>
    args.op()
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/bin/..nixops-wrapped-wrapped", line 379, in op_deploy
    repair=args.repair, dry_activate=args.dry_activate)
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/lib/python2.7/site-packages/nixops/deployment.py", line 990, in deploy
    self._deploy(**kwargs)
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/lib/python2.7/site-packages/nixops/deployment.py", line 947, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/lib/python2.7/site-packages/nixops/deployment.py", line 920, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/lib/python2.7/site-packages/nixops/backends/ec2.py", line 971, in create
    self._assign_elastic_ip(elastic_ipv4, check)
  File "/nix/store/0h2c0k9mr8y5pvjd3ml30ms5rdf4kia1-nixops-1.5.1/lib/python2.7/site-packages/nixops/backends/ec2.py", line 597, in _assign_elastic_ip
    self._conn.disassociate_address(public_ip=self.elastic_ipv4)
  File "/nix/store/n5irc6vd4wlf4g7ya3mii7f8819gci49-python2.7-boto-2.45.0/lib/python2.7/site-packages/boto/ec2/connection.py", line 2046, in disassociate_address
    return self.get_status('DisassociateAddress', params, verb='POST')
  File "/nix/store/n5irc6vd4wlf4g7ya3mii7f8819gci49-python2.7-boto-2.45.0/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>You must specify an association id when unmapping an address from a VPC instance</Message></Error></Errors><RequestID>5cda77cc-a1d9-4404-a95b-228ad8b4f5ca</RequestID></Response
````

**Comment by domenkozar** [comment]
@AmineChikhaoui is this still a bug that exists?

**Comment by AmineChikhaoui** [comment]
@domenkozar should be fixed once #697 is merged as I did a rewrite of the eip resource there. BTW after looking again it will likely need a schema upgrade of existing eips to make current deployments work, will add it to the todo list.

**Comment by AmineChikhaoui** [comment]
hm actually this is still an issue
