### ISSUE TITLE
ImportError: No module named google_compute_engine

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixops#693]
https://travis-ci.org/cleverca22/nixops-bug/branches
https://github.com/cleverca22/nixops-bug/branches

after several days of trying to figure out why nearly identical `.travis.yml` files had entirely different outcomes, i tracked it down
the mere presence of a sudo command in the `.travis.yml` file causes travis to use a different version of ubuntu (14.04 with sudo, 12.04 without sudo)

and there is an impurity somewhere within nixops, that causes it to fail under 14.04

**Comment by domenkozar** [comment]
The gist is:

```
$ nixops --version
Traceback (most recent call last):
  File "/nix/store/cjpnvn1fdimq960xslzyxlg4nc53gzlc-nixops-2017-05-22/bin/..nixops-wrapped-wrapped", line 5, in <module>
    from nixops import deployment
  File "/nix/store/cjpnvn1fdimq960xslzyxlg4nc53gzlc-nixops-2017-05-22/lib/python2.7/site-packages/nixops/deployment.py", line 1207, in <module>
    _load_modules_from("backends")
  File "/nix/store/cjpnvn1fdimq960xslzyxlg4nc53gzlc-nixops-2017-05-22/lib/python2.7/site-packages/nixops/deployment.py", line 1205, in _load_modules_from
    __import__("nixops." + dir + "." + module[:-3], globals(), locals())
  File "/nix/store/cjpnvn1fdimq960xslzyxlg4nc53gzlc-nixops-2017-05-22/lib/python2.7/site-packages/nixops/backends/ec2.py", line 10, in <module>
    import boto.ec2
  File "/nix/store/3nvdlwjppqw3vs53nk7wrncs87akgqcj-python2.7-boto-2.47.0/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/nix/store/3nvdlwjppqw3vs53nk7wrncs87akgqcj-python2.7-boto-2.47.0/lib/python2.7/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/nix/store/3nvdlwjppqw3vs53nk7wrncs87akgqcj-python2.7-boto-2.47.0/lib/python2.7/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ImportError: No module named google_compute_engine
```

I see that wrapping logic changed in `/nix/store/0ynq648rqsr22xsdmiis29wff3vikdcb-nixops-1.5/bin/..nixops-wrapped-wrapped`, maybe @fridh can help us here :)

**Comment by FRidh** [comment]
@domenkozar what specifically changed? `wrapPythonPrograms` now only wraps inside `/bin`, and we "fixed" pip by using a newer pkg_resources but aside from that nothing has changed. 

Is the sandbox used when building on Travis?

**Comment by cleverca22** [comment]
`- export PYTHONPATH=` doesn't fix nixops under a 14.04 travis

**Comment by spinus** [comment]
https://github.com/GoogleCloudPlatform/compute-image-packages/issues/262 - probably related

**Comment by domenkozar** [comment]
@cleverca22 can you try deleting `/etc/boto.cfg`?

I have pushed google-compute-engine python package in 0945a5b462c228595fbbc5df42ffca72bc1ebcdc, but of course it has a cyclic dependency on boto.

**Comment by domenkozar** [comment]
Travis-ci issue: https://github.com/travis-ci/travis-ci/issues/7940

**Comment by spinus** [comment]
my workaround is adding: `sudo rm /etc/boto*` to before_script

**Comment by josegonzalez** [comment]
You can also set `export BOTO_CONFIG=/dev/null` whenever you run tests.
