### ISSUE TITLE
"assert self.private_ipv4" on nixops check

### ISSUE THREAD

**Issue by teto** [NixOS/nixops#726]
So I was following the manual to discover nixops a bit:
https://nixos.org/nixops/manual/#idm140737318606112

when I stumbled on this:
```
nixops check -d example-libvirtd                                                                                                                                ~/nixpkgs
Traceback (most recent call last):
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/bin/..nixops-wrapped-wrapped", line 953, in <module>
    args.op()
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/bin/..nixops-wrapped-wrapped", line 277, in op_check
    results = run_tasks(nr_workers=len(machines), tasks=machines, worker_fun=worker)
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/bin/..nixops-wrapped-wrapped", line 251, in worker
    res = m.check()
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/backends/__init__.py", line 115, in check
    self._check(res)
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/backends/__init__.py", line 119, in _check
    avg = self.get_load_avg()
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/backends/__init__.py", line 102, in get_load_avg
    res = self.run_command("cat /proc/loadavg", capture_stdout=True, timeout=15).rstrip().split(' ')
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/backends/__init__.py", line 328, in run_command
    return self.ssh.run_command(command, self.get_ssh_flags(), **kwargs)
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/ssh_util.py", line 277, in run_command
    master = self.get_master(flags, timeout, user)
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/ssh_util.py", line 188, in get_master
    if self._host_fun() == "localhost":
  File "/nix/store/fg3rwslqrd6aqjwdiz206lzly2n2pp6q-nixops-1.5.1/lib/python2.7/site-packages/nixops/backends/libvirtd.py", line 215, in get_ssh_name
    assert self.private_ipv4
AssertionError

```
with NixOps 1.5.1

I use nixpkgs-unstable if that's relevant.

**Comment by teto** [comment]
fixed by https://github.com/NixOS/nixops/pull/783
