### ISSUE TITLE
change of ownership of a file (by nixops?) prevents libvirt using the file

### ISSUE THREAD

**Issue by teto** [NixOS/nixops#777]
I have an extension of the libvirt provider that accepts the libvirt kernel parameter which allows to start a vm with a host kernel cf https://libvirt.org/formatdomain.html#elementsOSKernel; code at https://github.com/teto/nixops/tree/kernel

My kernel /home/teto/mptcp/build_backup/vmlinux has the initial owners teto:libvirtd but after starting nixops the  owners of l /home/teto/mptcp/build_backup/vmlinux  become root:root and qemu fails to start/read it. Any idea where the ownership change could come from ?
```
libvirt: QEMU Driver error : internal error: process exited while connecting to monitor: 2017-11-21T17:18:41.800726Z qemu-system-x86_64: -chardev pty,id=charserial0: char device redirected to /dev/pts/11 (label charserial0)
qemu: could not load kernel '/home/teto/mptcp/build_backup/vmlinux': Permission denied
libvirt: QEMU Driver error : internal error: process exited while connecting to monitor: 2017-11-21T17:18:41.800724Z qemu-system-x86_64: -chardev pty,id=charserial0: char device redirected to /dev/pts/12 (label charserial0)
qemu: could not load kernel '/home/teto/mptcp/build_backup/vmlinux': Permission denied
error: Multiple exceptions: internal error: process exited while connecting to monitor: 2017-11-21T17:18:41.800726Z qemu-system-x86_64: -chardev pty,id=charserial0: char device redirected to /dev/pts/11 (label charserial0)
qemu: could not load kernel '/home/teto/mptcp/build_backup/vmlinux': Permission denied, internal error: process exited while connecting to monitor: 2017-11-21T17:18:41.800724Z qemu-system-x86_64: -chardev pty,id=charserial0: char device redirected to /dev/pts/12 (label charserial0)
qemu: could not load kernel '/home/teto/mptcp/build_backup/vmlinux': Permission denied
------------------------------
Traceback (most recent call last):
  File "/home/teto/nixops/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/home/teto/nixops/nixops/deployment.py", line 917, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/home/teto/nixops/nixops/backends/libvirtd.py", line 150, in create
    self.start()
  File "/home/teto/nixops/nixops/backends/libvirtd.py", line 260, in start
    self.dom.create()
  File "/nix/store/jpvh2gxw7mn6qiwc0c0wsppx67f7v1jk-libvirt-python-3.8.0/lib/python2.7/site-packages/libvirt.py", line 1069, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: internal error: process exited while connecting to monitor: 2017-11-21T17:18:41.800726Z qemu-system-x86_64: -chardev pty,id=charserial0: char device redirected to /dev/pts/11 (label charserial0)
qemu: could not load kernel '/home/teto/mptcp/build_backup/vmlinux': Permission denied
```

**Comment by teto** [comment]
Disabling dynamic ownership seems to solve this or let me work around it.
https://libvirt.org/git/?p=libvirt.git;a=commit;h=a691cb88f2fa9d4caaca12ed048ed487fdbc09e3

```
  virtualisation.libvirtd = {
    enable = true;
    qemuVerbatimConfig = ''
      namespaces = []

      # Whether libvirt should dynamically change file ownership
      dynamic_ownership = 0
      '';
  };

```
it s a libvirt problem, not nixops so I close this.
