### ISSUE TITLE
Creating Hetzner robot admin sub-account fails

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixops#778]
I get a `hetzner.WebRobotError` exception when provisioning a new Hetzner machine. This is with nixops-1.5.2 on NixOS-17.09.

When I upgrade nixops to the latest HEAD (https://github.com/NixOS/nixops/commit/92034401b5291070a93ede030e718bb82b5e6da4) I get the same error:

```
$ HETZNER_ROBOT_PASS=XXX nixops deploy -d my-net --include my-machine
my-machine...............................> 
creating an exclusive robot admin sub-account for ‘my-machine’... 
Traceback (most recent call last):
  File "/nix/store/p2a5cm95zwv67zawb3fm7jf5awqp5x64-nixops-1.6pre2276_9203440/bin/..nixops-wrapped-wrapped", line 955, in <module>
    args.op()
  File "/nix/store/p2a5cm95zwv67zawb3fm7jf5awqp5x64-nixops-1.6pre2276_9203440/bin/..nixops-wrapped-wrapped", line 382, in op_deploy
    repair=args.repair, dry_activate=args.dry_activate)
  File "/nix/store/p2a5cm95zwv67zawb3fm7jf5awqp5x64-nixops-1.6pre2276_9203440/lib/python2.7/site-packages/nixops/deployment.py", line 983, in deploy
    self._deploy(**kwargs)
  File "/nix/store/p2a5cm95zwv67zawb3fm7jf5awqp5x64-nixops-1.6pre2276_9203440/lib/python2.7/site-packages/nixops/deployment.py", line 944, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/p2a5cm95zwv67zawb3fm7jf5awqp5x64-nixops-1.6pre2276_9203440/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/p2a5cm95zwv67zawb3fm7jf5awqp5x64-nixops-1.6pre2276_9203440/lib/python2.7/site-packages/nixops/deployment.py", line 917, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/p2a5cm95zwv67zawb3fm7jf5awqp5x64-nixops-1.6pre2276_9203440/lib/python2.7/site-packages/nixops/backends/hetzner.py", line 599, in create
    self.robot_admin_pass) = server.admin.create()
  File "/nix/store/m6wybn3vn6fwjnb5wwlr48q0wyyhxcs4-python2.7-hetzner-0.7.5/lib/python2.7/site-packages/hetzner/server.py", line 374, in admin
    self._admin_account = AdminAccount(self)
  File "/nix/store/m6wybn3vn6fwjnb5wwlr48q0wyyhxcs4-python2.7-hetzner-0.7.5/lib/python2.7/site-packages/hetzner/server.py", line 170, in __init__
    self.update_info()
  File "/nix/store/m6wybn3vn6fwjnb5wwlr48q0wyyhxcs4-python2.7-hetzner-0.7.5/lib/python2.7/site-packages/hetzner/server.py", line 176, in update_info
    self._scraper.login()
  File "/nix/store/m6wybn3vn6fwjnb5wwlr48q0wyyhxcs4-python2.7-hetzner-0.7.5/lib/python2.7/site-packages/hetzner/robot.py", line 142, in login
    " page".format(response.status))
hetzner.WebRobotError
```

When I upgrade the `hetzner` python library to the latest HEAD with the following bugfix: https://github.com/RedMoonStudios/hetzner/pull/28 I get a different error:

```
$ HETZNER_ROBOT_PASS=XXX nixops deploy -d my-net --include my-machine
my-machine...............................> 
creating an exclusive robot admin sub-account for ‘my-machine’... 
error: Invalid status code 302 while visiting login page
```

@aszlig any idea what's going wrong?

**Comment by aszlig** [comment]
@basvandijk: Yep, Hetzner has changed their login mechanism for the Robot, see https://github.com/RedMoonStudios/hetzner/issues/26. I tried to fix it but it's a bit more involved, so maybe by the end of the week if there aren't any more surprises.

**Comment by basvandijk** [comment]
@aszlig thanks for showing the workaround!

Let me know if I can help in any way with fixing the login problem. Do you have to reverse engineer the login procedure or is there any API documentation?

**Comment by aszlig** [comment]
@basvandijk: I've fixed the login with RedMoonStudios/hetzner@2ed0b03c83cd5d1a3f02c5b6d59c9102c4b5b52a, can you try whether it works now with the latest master version of the `hetzner` library?

**Comment by basvandijk** [comment]
@aszlig with the latest master of the hetzner library nixops can now successfully create a sub-account. Thanks!

Now I face a new problem:

```
$ HETZNER_ROBOT_PASS=XXX nixops deploy -d my-net --include my-machine
my-machine...............................> installing machine...
my-machine...............................> rebooting machine ‘my-machine’ (XXX.XXX.XXX.XXX) into rescue system
my-machine...............................> sending reboot command... 
my-machine...............................> could not connect to ‘root@XXX.XXX.XXX.XXX’, retrying in 1 seconds...
my-machine...............................> could not connect to ‘root@XXX.XXX.XXX.XXX’, retrying in 2 seconds...
my-machine...............................> could not connect to ‘root@XXX.XXX.XXX.XXX’, retrying in 4 seconds...
my-machine...............................> could not connect to ‘root@XXX.XXX.XXX.XXX’, retrying in 8 seconds...
error: unable to start SSH master connection to ‘root@XXX.XXX.XXX.XXX’
```

**Comment by basvandijk** [comment]
It's working now. The problem was that by default I specify:

```
deployment.targetPort = nonStandardSshPort
```

I had to temporarily switch it to 22.

**Comment by aszlig** [comment]
@basvandijk: Hm, I wonder why it failed on reboot and not way before rebooting while `ssh`ing to the rescue system?

**Comment by basvandijk** [comment]
@aszlig it did fail when [trying to reboot to the rescue system](https://github.com/NixOS/nixops/blob/master/nixops/backends/hetzner.py#L618).

I think it's a good idea to make a new release of your `hetzner` library, upgrade it in nixpkgs and cherry-pick it on `release-17.09`. After that we can close this issue.
