### ISSUE TITLE
"string index out of range" error with VirtualBox backend

### ISSUE THREAD

**Issue by thorstenweber83** [NixOS/nixops#791]
with virtualbox 5.2.2r119230

nixops always dies with
```
Traceback (most recent call last):
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/bin/..nixops-wrapped-wrapped", line 955, in <module>
    args.op()
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/bin/..nixops-wrapped-wrapped", line 382, in op_deploy
    repair=args.repair, dry_activate=args.dry_activate)
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/deployment.py", line 983, in deploy
    self._deploy(**kwargs)
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/deployment.py", line 944, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/deployment.py", line 917, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 179, in create
    if self.state != self.UP or check: self.check()
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/__init__.py", line 115, in check
    self._check(res)
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 449, in _check
    state = self._get_vm_state()
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 117, in _get_vm_state
    vminfo = self._get_vm_info(can_fail)
  File "/nix/store/cqr665674h9v5akdzpdnh8bjy3m8dnzz-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/virtualbox.py", line 111, in _get_vm_info
    vminfo[k] = v if v[0]!='"' else v[1:-1]
IndexError: string index out of range
```

it's caused by `VBoxManage showvminfo --machinereadable` not always printing empty strings for empty values:
```
[...]
audio="pulse"
audio_in="true"
audio_out="true"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
videocap="off"
videocapscreens=0
videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=
GuestMemoryBalloon=0
```
as you can see in the line `videocapopts=`

I'll put up a pull request to fix this.

**Comment by thorstenweber83** [comment]
nevermind. it's already fixed in master :)

**Comment by supermario** [comment]
Ran into this issue and couldn't figure out how to get upgraded.

Ended up going with `nix-env -i nixops-1.6pre2276_9203440` (based on output of `nix-env -qaP nixops`) - hopefully that helps someone.
