### ISSUE TITLE
You must specify an allocation id when releasing a VPC elastic IP address

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixops#852]
Nixops commit: a6e608919bf57fd9b89985768693805dbbe53131 

```
xx-ip.........................> releasing elastic IP 18.196.XX.XX
xx2-ip............................> releasing elastic IP 52.57.XX.XX
error: Multiple exceptions: An error occurred (InvalidParameterValue) when calling the ReleaseAddress operation: You must specify an allocation id when releasing a VPC elastic IP address, An error occurred (InvalidParameterValue) when calling the ReleaseAddress operation: You must specify an allocation id when releasing a VPC elastic IP address
------------------------------
Traceback (most recent call last):
  File "/nix/store/rc4a2qdxhlwnpanggfj0y61gkhl3qpq2-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/rc4a2qdxhlwnpanggfj0y61gkhl3qpq2-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1091, in worker
    if m.destroy(wipe=wipe): self.delete_resource(m)
  File "/nix/store/rc4a2qdxhlwnpanggfj0y61gkhl3qpq2-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/resources/elastic_ip.py", line 124, in destroy
    self._client.release_address(PublicIp=eip['PublicIp'])
  File "/nix/store/419f6n7jvdycgsyx64xxr9wn5s5x12ap-python2.7-botocore-1.5.71/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/nix/store/419f6n7jvdycgsyx64xxr9wn5s5x12ap-python2.7-botocore-1.5.71/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterValue) when calling the ReleaseAddress operation: You must specify an allocation id when releasing a VPC elastic IP address
------------------------------
Traceback (most recent call last):
  File "/nix/store/rc4a2qdxhlwnpanggfj0y61gkhl3qpq2-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/rc4a2qdxhlwnpanggfj0y61gkhl3qpq2-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1091, in worker
    if m.destroy(wipe=wipe): self.delete_resource(m)
  File "/nix/store/rc4a2qdxhlwnpanggfj0y61gkhl3qpq2-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/resources/elastic_ip.py", line 124, in destroy
    self._client.release_address(PublicIp=eip['PublicIp'])
  File "/nix/store/419f6n7jvdycgsyx64xxr9wn5s5x12ap-python2.7-botocore-1.5.71/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/nix/store/419f6n7jvdycgsyx64xxr9wn5s5x12ap-python2.7-botocore-1.5.71/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterValue) when calling the ReleaseAddress operation: You must specify an allocation id when releasing a VPC elastic IP address
```

**Comment by domenkozar** [comment]
cc @AmineChikhaoui @rbvermaa

**Comment by AmineChikhaoui** [comment]
@domenkozar hm I can't reproduce, did the domain of the EIP changed from outside nixops ?

**Comment by deepfire** [comment]
@AmineChikhaoui, domain of the EIP?  May I ask you to clarify?

**Comment by AmineChikhaoui** [comment]
@deepfire There is standard (ec2 classic) and vpc domains for elastic ips, so I thought maybe the resource was deployed as standard first then moved to vpc from outside nixops ?

**Comment by deepfire** [comment]
@AmineChikhaoui, no, certainly not -- all managed from start to end.

The EIPs are still allocated, by the way.

**Comment by deepfire** [comment]
After manually deleting the EIPs on AWS, the `nixops destroy` was able to proceed.

**Comment by AmineChikhaoui** [comment]
@deepfire ah I see the issue now, just reproduced with a recent AWS account which is VPC only.
So this is a valid issue, thanks. You may as a workaround use `vpc = true;` in the resource config for now when you create it.
