### ISSUE TITLE
can't run nixops (ImportError: cannot import name _remove_dead_weakref)

### ISSUE THREAD

**Issue by alpmestan** [NixOS/nixops#867]
Hello,

I know this might be a nixops issue per se (but one with my environment instead), but my lack of knowledge regarding how python stuffs are handled in nixpkgs makes me inclined to come here and ask fellow nix(ops) users.

So, without further ado:

``` sh
$ nix-shell --pure -p nixops --run 'nixops'
usage: nixops [-h] [--version]
              {list,create,modify,clone,delete,info,check,set-args,deploy,send-keys,destroy,stop,start,reboot,show-arguments,show-physical,ssh,ssh-for-each,scp,mount,rename,backup,backup-status,remove-backup,clean-backups,restore,show-option,list-generations,rollback,delete-generation,show-console-output,dump-nix-paths,export,import,edit}
              ...
nixops: error: too few arguments
$ nix-shell -p nixops --run 'nixops'
Traceback (most recent call last):
  File "/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/bin/..nixops-wrapped-wrapped", line 5, in <module>
    from nixops import deployment
  File "/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/lib/python2.7/site-packages/nixops/deployment.py", line 16, in <module>
    import nixops.backends
  File "/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/lib/python2.7/site-packages/nixops/backends/__init__.py", line 7, in <module>
    import nixops.util
  File "/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/lib/python2.7/site-packages/nixops/util.py", line 7, in <module>
    import copy
  File "/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

I'm suspecting that my (nixos) system configuration is somehow interacting with this and messing things up. For what it's worth:

``` sh
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-17.09
```

I'm at the tip of that channel, up-to-date. Also possibly relevant, the PYTHONPATH with and without `--pure`.

``` sh
$ nix-shell -p nixops --run 'env | grep PYTHONPATH'
PYTHONPATH=/nix/store/hp65d1nx6l8gf7w55kww80dix9mvdsrl-guake-0.8.3/lib/python2.7/site-packages:/nix/store/sxxy3xn59gmpxvp0wxm230ync0rsl6gw-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages:/nix/store/0papxibkys4wjphz5zszv11x9p68gcls-python-notify-0.1.1/lib/python2.7/site-packages:/nix/store/1c4hqmhb3fgnhvsdi7px47jd1qff6ij8-python2.7-pygtk-2.24.0/lib/python2.7/site-packages:/nix/store/wpqy3z4bcss3fz7gm4xwfzjk5f3wqsn6-python2.7-pyxdg-0.25/lib/python2.7/site-packages:/nix/store/zppd5gb29d9r4731qfdb69mvkk6j17d3-gnome-python-2.28.1/lib/python2.7/site-packages:/nix/store/7dxqxqc68xfhip2rzi6vqn552f0f7phk-python-2.7.13/lib/python2.7/site-packages:/nix/store/w72lapmrhlybf4q6zsh9h70nn9w8ziyb-vte-0.28.2/lib/python2.7/site-packages:/nix/store/3xmkrvhwsfnzkxz74rlsrcwiaznmd1dk-keybinder-0.3.0/lib/python2.7/site-packages:/nix/store/1c4hqmhb3fgnhvsdi7px47jd1qff6ij8-python2.7-pygtk-2.24.0/lib/python2.7/site-packages:/nix/store/9lr8rwmn7igbh53357c41z34crx246mh-python2.7-pygobject-2.28.6/lib/python2.7/site-packages:/nix/store/1izxyl3ymd25pqb0ql6bzwjavl5qw1zx-python2.7-setuptools-30.2.0/lib/python2.7/site-packages:/nix/store/cpaikxgba1i61m1vr5ip2jdx27gypm6m-python2.7-pycairo-1.10.0/lib/python2.7/site-packages:/nix/store/wpqy3z4bcss3fz7gm4xwfzjk5f3wqsn6-python2.7-pyxdg-0.25/lib/python2.7/site-packages:/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/lib/python2.7/site-packages:/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/site-packages:/nix/store/a1qr0l3kf2yig3xfy68ypyxvg6pd3dwl-python2.7-setuptools-36.4.0/lib/python2.7/site-packages

$ nix-shell --pure -p nixops --run 'env | grep PYTHONPATH'
PYTHONPATH=/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/lib/python2.7/site-packages:/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/site-packages:/nix/store/a1qr0l3kf2yig3xfy68ypyxvg6pd3dwl-python2.7-setuptools-36.4.0/lib/python2.7/site-packages
```

In addition to that, I saw that nixops ends up doing some PYTHONPATH manipulations of its own in some python script:

``` python
$ cat /nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/bin/..nixops-wrapped-wrapped 
#!/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/bin/python2.7
# -*- coding: utf-8 -*-

import sys;import site;import functools;sys.argv[0] = '/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/bin/.nixops-wrapped';fun
ctools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/3zcy2vladp290nqf3d8bm0nvmizvn740-nixops-1.5.2/lib/python2.7/site-packages
','/nix/store/a1qr0l3kf2yig3xfy68ypyxvg6pd3dwl-python2.7-setuptools-36.4.0/lib/python2.7/site-packages','/nix/store/nan0p067vv7qna547552
clqv8mwbn1hn-python2.7-prettytable-0.7.1/lib/python2.7/site-packages','/nix/store/dy5kc9wm1fay29472j9icp717pmfr2fw-python2.7-boto-2.47.0
/lib/python2.7/site-packages','/nix/store/l7h7wdswxk5p8wv54hrmj7rdilq3yxfv-python2.7-urllib3-1.22/lib/python2.7/site-packages','/nix/sto
re/wmi7bgd0z21lzhbyjyn4klighazrpmzm-python2.7-idna-2.5/lib/python2.7/site-packages','/nix/store/n8ix8r47cx37kjf241v3bnc06w7wsjqk-python2
.7-asn1crypto-0.22.0/lib/python2.7/site-packages','/nix/store/3009w44cd74zmazsc4js3qlw21fmkkgi-python2.7-packaging-16.8/lib/python2.7/si
te-packages','/nix/store/nzaiasm7icsbka7vsgzc9yfcbyzfdiks-python2.7-pyparsing-2.2.0/lib/python2.7/site-packages','/nix/store/7zap9m8xnad
57mi0fwqfjs1qi77y653n-python2.7-six-1.10.0/lib/python2.7/site-packages','/nix/store/b20p1kv06fq036vl2vmv17ads5b2zrdh-python2.7-enum34-1.
1.6/lib/python2.7/site-packages','/nix/store/fk5wj43gmw8fxv294q3h7kci101wzbmn-python2.7-ipaddress-1.0.18/lib/python2.7/site-packages','/
nix/store/kxsyxyxjxyzm58w1ka83iv5hhz2yjwrl-python2.7-pycparser-2.14/lib/python2.7/site-packages','/nix/store/f1iv4kw47qvp72v97gwx6imdqi5
7d5a4-python2.7-cffi-1.10.0/lib/python2.7/site-packages','/nix/store/zm59nl5w5y6skjkabag0si23wh2nxca0-python2.7-cryptography-2.0.3/lib/p
ython2.7/site-packages','/nix/store/inxc1lqpl0cx3i4ibp267p2wv4pdbcvn-python2.7-pyasn1-0.1.9/lib/python2.7/site-packages','/nix/store/rxh
2a3n5mig3qs1rm2ycmbb932rarkcq-python2.7-pyOpenSSL-17.2.0/lib/python2.7/site-packages','/nix/store/x3w5yqp2brd30izzbwfbzasqsd5rry0z-pytho
n2.7-certifi-2017.7.27.1/lib/python2.7/site-packages','/nix/store/fcw48ahm31j1d3ik3z7ja035fbb5afrq-python2.7-pysocks-1.6.6/lib/python2.7
/site-packages','/nix/store/09ilmwwllmdc5kr7yp1fr42smcinr4p1-python2.7-chardet-3.0.4/lib/python2.7/site-packages','/nix/store/xkhz9gcrlk
56hndvwydqnfzwvlryj3b5-python2.7-requests-2.18.4/lib/python2.7/site-packages','/nix/store/wk1rc90rzx8z57mkbd9iyslyyn1vjxfq-python2.7-htt
pretty-0.8.10/lib/python2.7/site-packages','/nix/store/xq2vsqn75i86n2c1pb4nlqb1xjq5m1qm-python2.7-boto3-1.4.8/lib/python2.7/site-package
s','/nix/store/26jbv2s2b3zjnv7h3xblrjys9wqvp22h-python2.7-botocore-1.8.26/lib/python2.7/site-packages','/nix/store/8l29svj6iasmjissfvcjs
hi75b27fgwn-python2.7-python-dateutil-2.6.1/lib/python2.7/site-packages','/nix/store/5rmfgimgx0mawkfp9v7lix33cs5mjnnf-python2.7-jmespath
-0.9.0/lib/python2.7/site-packages','/nix/store/4qqm3q10cvmp1gdwgrygb6rjpzpadr8i-python2.7-ply-3.8/lib/python2.7/site-packages','/nix/st
ore/q5wqxw1n6r7saln968f5rmrjs6l1qs6j-python2.7-s3transfer-0.1.12/lib/python2.7/site-packages','/nix/store/xxar9n89g0v56xzdlxxqi0hg481kav
ib-python2.7-futures-3.0.5/lib/python2.7/site-packages','/nix/store/81agv03z6k976whw90ccvjiqc0v5kaif-python2.7-hetzner-0.8.0/lib/python2
.7/site-packages','/nix/store/w5278xccblmjfng3a60sxfn9r88xh63c-python2.7-libcloud-1.2.1/lib/python2.7/site-packages','/nix/store/z7flhfy
flkdy7k5vigrvrjm187rkb0ml-python2.7-pycrypto-3.4.7/lib/python2.7/site-packages','/nix/store/cvz3an0mx2snkkvq3wa9jsyckvg5kq1s-python2.7-p
ycryptodome-3.4.7/lib/python2.7/site-packages','/nix/store/d4ar0rdiw70zhsbpwnpvi9ih7n19xnfq-python2.7-azure-storage-0.20.3/lib/python2.7
/site-packages','/nix/store/skzhcjn82xiza1k8pag13lz5prr8k84v-python2.7-azure-common-1.0.0/lib/python2.7/site-packages','/nix/store/ddjj5
7l6nsf4ljhcsgkxyb44zgl5hzcg-python2.7-azure-nspkg-1.0.0/lib/python2.7/site-packages','/nix/store/rjbqs8hbc2qp99xkzi8l35imi1j0z902-python
2.7-azure-mgmt-compute-0.20.0/lib/python2.7/site-packages','/nix/store/a0r3nxabgvf1lpc1mkdlmixxwc8la94r-python2.7-azure-mgmt-common-0.20
.0/lib/python2.7/site-packages','/nix/store/k3hxfkqi4glh922safgv2wim5yjqnx33-python2.7-azure-mgmt-nspkg-1.0.0/lib/python2.7/site-package
s','/nix/store/pmhdi6xc05gabi674d1n36k943301xi5-python2.7-azure-mgmt-network-0.20.1/lib/python2.7/site-packages','/nix/store/nbhzdpmx3y7
p1xwafgi9r0kzqzyn3pjb-python2.7-azure-mgmt-resource-0.20.1/lib/python2.7/site-packages','/nix/store/h87ixqmpys2idkh13h40gvyv9f6b85f3-pyt
hon2.7-azure-mgmt-storage-0.20.0/lib/python2.7/site-packages','/nix/store/17981c94gca2n68am1r0psw5k1xz031q-python2.7-adal-0.4.7/lib/pyth
on2.7/site-packages','/nix/store/4g9b87nqbfwlmcgwjx24hmybqwp5cnfh-python2.7-pyjwt-1.5.3/lib/python2.7/site-packages','/nix/store/q1zc2hc
d271f2znh4bwslrd9qn8jkwaj-python2.7-ecdsa-0.13/lib/python2.7/site-packages','/nix/store/slic6s8k1lv25818lj062w4lrsqnfcj9-python2.7-pysql
ite-2.8.3/lib/python2.7/site-packages','/nix/store/dml69cn3ib8jy227k3js7r6hc0zaksis-python2.7-datadog-0.10.0/lib/python2.7/site-packages
','/nix/store/7q929pa8gixkllhiwqril5z82719g9ck-python2.7-decorator-4.0.11/lib/python2.7/site-packages','/nix/store/dr2k4dbffaq3j148jpzh8
yj83bi4lk4b-python2.7-simplejson-3.11.1/lib/python2.7/site-packages','/nix/store/rcq003slawblsambn2x2mndz28r3374c-python2.7-python-digit
alocean-1.10.1/lib/python2.7/site-packages'], site._init_pathinfo());
[...]
```

So I suppose that the larger PYTHONPATH is somehow messing with things here, but I have no idea how/why. Note that nixops is not the only affected program (`virt-manager` is as well for example), but I really care about being able to use `nixops` right now (and I'm not sure I want to figure out the complete environment required to run nixops in a pure nix shell...).

Does anyone see what's going wrong here and what needs to be done to fix it? Thanks in advance!

**Comment by aycanirican** [comment]
Hi Alp,

If you want to quickly upgrade to the latest nixops (which is working for me right now), you may want to use such a shell.nix file:

nixpkgs.json:

{
  "url": "https://github.com/nixos/nixpkgs.git",
  "rev": "aaa4cd02d96bf2d1110be08a68eb68a9187e94cb",
  "date": "2018-01-29T15:30:48-05:00",
  "sha256": "0wvp3c34ccsbqq4qp1i3xyv4yi9zskak5827d312403ywg9zx1ad",
  "fetchSubmodules": true
}

shell.nix:

let
  _pkgs = import <nixpkgs> {};
  nixpkgsRepo = _pkgs.lib.importJSON ./nixpkgs.json;
  nixpkgsSrc = _pkgs.fetchFromGitHub { owner = "NixOS"; repo = "nixpkgs"; inherit (nixpkgsRepo) rev sha256; };

  pkgs = (import nixpkgsSrc {});

  nixopsSrc = builtins.fetchTarball https://github.com/NixOS/nixops/archive/4feccf323f0c166dd3e55dfe3015feab1d25dfe3.tar.gz;
  nixops-latest = (import "${nixopsSrc}/release.nix" {});
in pkgs.stdenv.mkDerivation rec {
  name = "nixops-env";
  buildInputs = with pkgs; [ openssl awscli nixops-latest.build.x86_64-linux ];
  shellHook = ''
    . ~/.aws/vars
    export NIX_PATH=${pkgs.path}:nixpkgs=${pkgs.path}:.
  '';
}

—
aycan

**Comment by alpmestan** [comment]
@aycanirican Thanks for dropping by! Unfortunately, my environment being somehow messed up means that your shell doesn't work on my machine either, unless I make it `--pure` in which case it cannot find everything it needs and this becomes rather painful.

``` sh
$ nix-shell --pure --command 'nixops deploy -d server'
error: unable to run ‘nix-instantiate’: [Errno 2] No such file or directory

$ nix-shell --command 'nixops deploy -d server'
Traceback (most recent call last):
  File "/nix/store/0vjx4w980v2cdb50180b1j3ml56nr9zd-nixops-1.6pre0_abcdef/bin/.nixops-wrapped", line 5, in <module>
    from nixops import deployment
  File "/nix/store/0vjx4w980v2cdb50180b1j3ml56nr9zd-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 16, in <module>
    import nixops.backends
  File "/nix/store/0vjx4w980v2cdb50180b1j3ml56nr9zd-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/backends/__init__.py", line 7, in <module>
    import nixops.util
  File "/nix/store/0vjx4w980v2cdb50180b1j3ml56nr9zd-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/util.py", line 7, in <module>
    import copy
  File "/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

If you have any tips for figuring out what's causing this, I'm all ears =) My best lead is to do a "diff" of the output of `env` in both shells and try to figure out from there (mecanically or automatically) what env var is causing the problem. I've already tried running nixops with `env PYTHONPATH=  nixops`, which should prevent my default environment's python stuffs from interacting with nixops. But same result. Note that the nixops wrapper does its own thing for the PYTHONPATH so maybe it's the script that picks the wrong things?

Also, both shells are trying to use the very same python-2.7.14 derivation, and I can't even import `weakref` there:

``` sh
# not from a nix-shell, just my default user environment
$ /nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/bin/python
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import weakref
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

And if we focus on python 2.7.14:

``` sh
$ nix-shell -p python27 --command 'python'
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import weakref
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/i3bx1iw2d0i3vh9sa1nf92ynlrw324w8-python-2.7.14/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
>>> 

$ nix-shell --pure -p python27 --command 'python'
Python 2.7.14 (default, Sep 16 2017, 17:49:51) 
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import weakref
>>>
```

**Comment by alpmestan** [comment]
... I just realized that a different 'python' is executed in the first case.

**Comment by alpmestan** [comment]
I see `"/nix/store/7dxqxqc68xfhip2rzi6vqn552f0f7phk-python-2.7.13/lib/python2.7/site-packages"` in the PYTHONPATH for the impure shell. Now I just have to find out who's stuck using 2.7.13. Sorry for the noise.
