### ISSUE TITLE
Backtraces are broken

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixops#886]
version: master.

Perhaps only Python 3 is supported, but in that case it should refuse to run in anything else.

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "/nix/store/4522fj50rfzb9lzm8g4ms6wb5bddb5db-nixops-1.6pre0_abcdef/bin/.nixops-wrapped", line 995, in <module>
    e.print_all_backtraces()
  File "/nix/store/4522fj50rfzb9lzm8g4ms6wb5bddb5db-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/parallel.py", line 20, in print_all_backtraces
    traceback.print_exception(e[0], e[1], e[2])
  File "/nix/store/cs3g9k4vgazvlv25kp3akscdvdjc8675-python-2.7.14/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/nix/store/cs3g9k4vgazvlv25kp3akscdvdjc8675-python-2.7.14/lib/python2.7/traceback.py", line 61, in print_tb
    f = tb.tb_frame
AttributeError: 'str' object has no attribute 'tb_frame'
```

**Comment by teto** [comment]
would be cool to fix this as it hampers development. I am working on a branch  and I am not sure how to get the proper exceptions. 
with
```
    def print_all_backtraces(self):
        for e in self.exceptions:
            sys.stderr.write('-'*30 + '\n')
            print("%r" % e)
```
I get a  u'client' with libvirt provider
