### ISSUE TITLE
libvirt virNetworkGetDHCPLeases error on 18.03

### ISSUE THREAD

**Issue by nh2** [NixOS/nixops#973]
With up upgrade to nixpkgs `release-18.03`, I started seeing this in about 50% of my libvirt nixops deployments:

```
node-3..> uploading key ‘mykey’...
libvirt: Network Driver error : invalid network pointer in virNetworkGetDHCPLeases
node-1..> error: Traceback (most recent call last):
  File "/nix/store/p80ilh2vvk82h4cvysca3s31v2ak2rms-python2.7-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 715, in worker
    m.send_keys()
  File "/nix/store/p80ilh2vvk82h4cvysca3s31v2ak2rms-python2.7-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/backends/__init__.py", line 281, in send_keys
    self.upload_file(tmp, tmp_outfile)
  File "/nix/store/p80ilh2vvk82h4cvysca3s31v2ak2rms-python2.7-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/backends/__init__.py", line 431, in upload_file
    cmdline += [source, "root@" + self.get_ssh_name() + ":" + target]
  File "/nix/store/p80ilh2vvk82h4cvysca3s31v2ak2rms-python2.7-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/backends/libvirtd.py", line 267, in get_ssh_name
    self.private_ipv4 = self._parse_ip()
  File "/nix/store/p80ilh2vvk82h4cvysca3s31v2ak2rms-python2.7-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/backends/libvirtd.py", line 226, in _parse_ip
    ifaces = self.dom.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE, 0)
  File "/nix/store/jzjp87fbh4k2kdf5vky3gyddipq6d74f-python2.7-libvirt-3.10.0/lib/python2.7/site-packages/libvirt.py", line 1347, in interfaceAddresses
    if ret is None: raise libvirtError ('virDomainInterfaceAddresses() failed', dom=self)
libvirtError: invalid network pointer in virNetworkGetDHCPLeases
```

Not sure what that is; googling `invalid network pointer in virNetworkGetDHCPLeases` yields 0 results.

**Comment by nh2** [comment]
I've tried a luckshot upgrading from libvirt 3.10.0 -> 4.4 but it didn't fix it.

**Comment by teto** [comment]
You could try this PR https://github.com/NixOS/nixops/pull/922. I had to modify a few things to make it more reliable

**Comment by nh2** [comment]
If I remember correctly, I tried this a couple months ago but it didn't fix it for me.
